// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: analysis.proto

package analysisproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TypeKind int32

const (
	TypeKind_TYPE_KIND_UNKNOWN TypeKind = 0
	TypeKind_TYPE_KIND_STRUCT  TypeKind = 1
	TypeKind_TYPE_KIND_CLASS   TypeKind = 2
	TypeKind_TYPE_KIND_ENUM    TypeKind = 3
	TypeKind_TYPE_KIND_ACTOR   TypeKind = 4
)

// Enum value maps for TypeKind.
var (
	TypeKind_name = map[int32]string{
		0: "TYPE_KIND_UNKNOWN",
		1: "TYPE_KIND_STRUCT",
		2: "TYPE_KIND_CLASS",
		3: "TYPE_KIND_ENUM",
		4: "TYPE_KIND_ACTOR",
	}
	TypeKind_value = map[string]int32{
		"TYPE_KIND_UNKNOWN": 0,
		"TYPE_KIND_STRUCT":  1,
		"TYPE_KIND_CLASS":   2,
		"TYPE_KIND_ENUM":    3,
		"TYPE_KIND_ACTOR":   4,
	}
)

func (x TypeKind) Enum() *TypeKind {
	p := new(TypeKind)
	*p = x
	return p
}

func (x TypeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TypeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_analysis_proto_enumTypes[0].Descriptor()
}

func (TypeKind) Type() protoreflect.EnumType {
	return &file_analysis_proto_enumTypes[0]
}

func (x TypeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TypeKind.Descriptor instead.
func (TypeKind) EnumDescriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{0}
}

type MemberSourceKind int32

const (
	MemberSourceKind_MEMBER_SOURCE_KIND_UNKNOWN  MemberSourceKind = 0
	MemberSourceKind_MEMBER_SOURCE_KIND_PROPERTY MemberSourceKind = 1
	MemberSourceKind_MEMBER_SOURCE_KIND_METHOD   MemberSourceKind = 2
)

// Enum value maps for MemberSourceKind.
var (
	MemberSourceKind_name = map[int32]string{
		0: "MEMBER_SOURCE_KIND_UNKNOWN",
		1: "MEMBER_SOURCE_KIND_PROPERTY",
		2: "MEMBER_SOURCE_KIND_METHOD",
	}
	MemberSourceKind_value = map[string]int32{
		"MEMBER_SOURCE_KIND_UNKNOWN":  0,
		"MEMBER_SOURCE_KIND_PROPERTY": 1,
		"MEMBER_SOURCE_KIND_METHOD":   2,
	}
)

func (x MemberSourceKind) Enum() *MemberSourceKind {
	p := new(MemberSourceKind)
	*p = x
	return p
}

func (x MemberSourceKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemberSourceKind) Descriptor() protoreflect.EnumDescriptor {
	return file_analysis_proto_enumTypes[1].Descriptor()
}

func (MemberSourceKind) Type() protoreflect.EnumType {
	return &file_analysis_proto_enumTypes[1]
}

func (x MemberSourceKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MemberSourceKind.Descriptor instead.
func (MemberSourceKind) EnumDescriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{1}
}

type MemberKind int32

const (
	MemberKind_MEMBER_KIND_UNKNOWN           MemberKind = 0
	MemberKind_MEMBER_KIND_INSTANCE_PROPERTY MemberKind = 1
	MemberKind_MEMBER_KIND_INSTANCE_METHOD   MemberKind = 2
	MemberKind_MEMBER_KIND_STATIC_PROPERTY   MemberKind = 3
	MemberKind_MEMBER_KIND_STATIC_METHOD     MemberKind = 4
	MemberKind_MEMBER_KIND_CONSTRUCTOR       MemberKind = 5
)

// Enum value maps for MemberKind.
var (
	MemberKind_name = map[int32]string{
		0: "MEMBER_KIND_UNKNOWN",
		1: "MEMBER_KIND_INSTANCE_PROPERTY",
		2: "MEMBER_KIND_INSTANCE_METHOD",
		3: "MEMBER_KIND_STATIC_PROPERTY",
		4: "MEMBER_KIND_STATIC_METHOD",
		5: "MEMBER_KIND_CONSTRUCTOR",
	}
	MemberKind_value = map[string]int32{
		"MEMBER_KIND_UNKNOWN":           0,
		"MEMBER_KIND_INSTANCE_PROPERTY": 1,
		"MEMBER_KIND_INSTANCE_METHOD":   2,
		"MEMBER_KIND_STATIC_PROPERTY":   3,
		"MEMBER_KIND_STATIC_METHOD":     4,
		"MEMBER_KIND_CONSTRUCTOR":       5,
	}
)

func (x MemberKind) Enum() *MemberKind {
	p := new(MemberKind)
	*p = x
	return p
}

func (x MemberKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemberKind) Descriptor() protoreflect.EnumDescriptor {
	return file_analysis_proto_enumTypes[2].Descriptor()
}

func (MemberKind) Type() protoreflect.EnumType {
	return &file_analysis_proto_enumTypes[2]
}

func (x MemberKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MemberKind.Descriptor instead.
func (MemberKind) EnumDescriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{2}
}

type PropertyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TypeExpr      string                 `protobuf:"bytes,2,opt,name=type_expr,json=typeExpr,proto3" json:"type_expr,omitempty"`
	BodyLine      int32                  `protobuf:"varint,3,opt,name=body_line,json=bodyLine,proto3" json:"body_line,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertyInfo) Reset() {
	*x = PropertyInfo{}
	mi := &file_analysis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyInfo) ProtoMessage() {}

func (x *PropertyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyInfo.ProtoReflect.Descriptor instead.
func (*PropertyInfo) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{0}
}

func (x *PropertyInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PropertyInfo) GetTypeExpr() string {
	if x != nil {
		return x.TypeExpr
	}
	return ""
}

func (x *PropertyInfo) GetBodyLine() int32 {
	if x != nil {
		return x.BodyLine
	}
	return 0
}

func (x *PropertyInfo) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type MethodInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Selector      string                 `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"`
	Signature     string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	BodyLine      int32                  `protobuf:"varint,4,opt,name=body_line,json=bodyLine,proto3" json:"body_line,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MethodInfo) Reset() {
	*x = MethodInfo{}
	mi := &file_analysis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodInfo) ProtoMessage() {}

func (x *MethodInfo) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodInfo.ProtoReflect.Descriptor instead.
func (*MethodInfo) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{1}
}

func (x *MethodInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MethodInfo) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *MethodInfo) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *MethodInfo) GetBodyLine() int32 {
	if x != nil {
		return x.BodyLine
	}
	return 0
}

func (x *MethodInfo) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type TypeInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind           TypeKind               `protobuf:"varint,2,opt,name=kind,proto3,enum=axe.analysis.TypeKind" json:"kind,omitempty"`
	AccessLevel    string                 `protobuf:"bytes,3,opt,name=access_level,json=accessLevel,proto3" json:"access_level,omitempty"`
	InheritedTypes []string               `protobuf:"bytes,4,rep,name=inherited_types,json=inheritedTypes,proto3" json:"inherited_types,omitempty"`
	Properties     []*PropertyInfo        `protobuf:"bytes,5,rep,name=properties,proto3" json:"properties,omitempty"`
	Methods        []*MethodInfo          `protobuf:"bytes,6,rep,name=methods,proto3" json:"methods,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TypeInfo) Reset() {
	*x = TypeInfo{}
	mi := &file_analysis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeInfo) ProtoMessage() {}

func (x *TypeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeInfo.ProtoReflect.Descriptor instead.
func (*TypeInfo) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{2}
}

func (x *TypeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TypeInfo) GetKind() TypeKind {
	if x != nil {
		return x.Kind
	}
	return TypeKind_TYPE_KIND_UNKNOWN
}

func (x *TypeInfo) GetAccessLevel() string {
	if x != nil {
		return x.AccessLevel
	}
	return ""
}

func (x *TypeInfo) GetInheritedTypes() []string {
	if x != nil {
		return x.InheritedTypes
	}
	return nil
}

func (x *TypeInfo) GetProperties() []*PropertyInfo {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *TypeInfo) GetMethods() []*MethodInfo {
	if x != nil {
		return x.Methods
	}
	return nil
}

type PreviewBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartLine     int32                  `protobuf:"varint,1,opt,name=start_line,json=startLine,proto3" json:"start_line,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewBlock) Reset() {
	*x = PreviewBlock{}
	mi := &file_analysis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewBlock) ProtoMessage() {}

func (x *PreviewBlock) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewBlock.ProtoReflect.Descriptor instead.
func (*PreviewBlock) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{3}
}

func (x *PreviewBlock) GetStartLine() int32 {
	if x != nil {
		return x.StartLine
	}
	return 0
}

func (x *PreviewBlock) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PreviewBlock) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type MemberSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeName      string                 `protobuf:"bytes,1,opt,name=type_name,json=typeName,proto3" json:"type_name,omitempty"`
	Line          int32                  `protobuf:"varint,2,opt,name=line,proto3" json:"line,omitempty"`
	Kind          MemberSourceKind       `protobuf:"varint,3,opt,name=kind,proto3,enum=axe.analysis.MemberSourceKind" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	TypeExpr      string                 `protobuf:"bytes,5,opt,name=type_expr,json=typeExpr,proto3" json:"type_expr,omitempty"`
	Signature     string                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	Selector      string                 `protobuf:"bytes,7,opt,name=selector,proto3" json:"selector,omitempty"`
	BodyLine      int32                  `protobuf:"varint,8,opt,name=body_line,json=bodyLine,proto3" json:"body_line,omitempty"`
	Source        string                 `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberSource) Reset() {
	*x = MemberSource{}
	mi := &file_analysis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberSource) ProtoMessage() {}

func (x *MemberSource) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberSource.ProtoReflect.Descriptor instead.
func (*MemberSource) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{4}
}

func (x *MemberSource) GetTypeName() string {
	if x != nil {
		return x.TypeName
	}
	return ""
}

func (x *MemberSource) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *MemberSource) GetKind() MemberSourceKind {
	if x != nil {
		return x.Kind
	}
	return MemberSourceKind_MEMBER_SOURCE_KIND_UNKNOWN
}

func (x *MemberSource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MemberSource) GetTypeExpr() string {
	if x != nil {
		return x.TypeExpr
	}
	return ""
}

func (x *MemberSource) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *MemberSource) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *MemberSource) GetBodyLine() int32 {
	if x != nil {
		return x.BodyLine
	}
	return 0
}

func (x *MemberSource) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type ParseResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Imports       []string               `protobuf:"bytes,2,rep,name=imports,proto3" json:"imports,omitempty"`
	Previews      []*PreviewBlock        `protobuf:"bytes,3,rep,name=previews,proto3" json:"previews,omitempty"`
	SkeletonHash  string                 `protobuf:"bytes,4,opt,name=skeleton_hash,json=skeletonHash,proto3" json:"skeleton_hash,omitempty"`
	MemberSources []*MemberSource        `protobuf:"bytes,7,rep,name=member_sources,json=memberSources,proto3" json:"member_sources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseResult) Reset() {
	*x = ParseResult{}
	mi := &file_analysis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseResult) ProtoMessage() {}

func (x *ParseResult) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseResult.ProtoReflect.Descriptor instead.
func (*ParseResult) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{5}
}

func (x *ParseResult) GetImports() []string {
	if x != nil {
		return x.Imports
	}
	return nil
}

func (x *ParseResult) GetPreviews() []*PreviewBlock {
	if x != nil {
		return x.Previews
	}
	return nil
}

func (x *ParseResult) GetSkeletonHash() string {
	if x != nil {
		return x.SkeletonHash
	}
	return ""
}

func (x *ParseResult) GetMemberSources() []*MemberSource {
	if x != nil {
		return x.MemberSources
	}
	return nil
}

type TypeFileMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Types         map[string]string      `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // typeName → filePath
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeFileMap) Reset() {
	*x = TypeFileMap{}
	mi := &file_analysis_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeFileMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeFileMap) ProtoMessage() {}

func (x *TypeFileMap) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeFileMap.ProtoReflect.Descriptor instead.
func (*TypeFileMap) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{6}
}

func (x *TypeFileMap) GetTypes() map[string]string {
	if x != nil {
		return x.Types
	}
	return nil
}

type IndexMemberInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // "body", "greet(name:)"
	Kind          MemberKind             `protobuf:"varint,2,opt,name=kind,proto3,enum=axe.analysis.MemberKind" json:"kind,omitempty"`
	AccessLevel   string                 `protobuf:"bytes,3,opt,name=access_level,json=accessLevel,proto3" json:"access_level,omitempty"` // "private", "internal", "public", etc.
	Line          int32                  `protobuf:"varint,4,opt,name=line,proto3" json:"line,omitempty"`
	Column        int32                  `protobuf:"varint,5,opt,name=column,proto3" json:"column,omitempty"`
	IsComputed    bool                   `protobuf:"varint,6,opt,name=is_computed,json=isComputed,proto3" json:"is_computed,omitempty"` // accessor occurrence の有無で判定
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexMemberInfo) Reset() {
	*x = IndexMemberInfo{}
	mi := &file_analysis_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexMemberInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexMemberInfo) ProtoMessage() {}

func (x *IndexMemberInfo) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexMemberInfo.ProtoReflect.Descriptor instead.
func (*IndexMemberInfo) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{7}
}

func (x *IndexMemberInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IndexMemberInfo) GetKind() MemberKind {
	if x != nil {
		return x.Kind
	}
	return MemberKind_MEMBER_KIND_UNKNOWN
}

func (x *IndexMemberInfo) GetAccessLevel() string {
	if x != nil {
		return x.AccessLevel
	}
	return ""
}

func (x *IndexMemberInfo) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *IndexMemberInfo) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

func (x *IndexMemberInfo) GetIsComputed() bool {
	if x != nil {
		return x.IsComputed
	}
	return false
}

type IndexTypeInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                             // ネスト型は "Outer.Inner"
	Kind           TypeKind               `protobuf:"varint,2,opt,name=kind,proto3,enum=axe.analysis.TypeKind" json:"kind,omitempty"` // 既存の TypeKind enum を再利用
	AccessLevel    string                 `protobuf:"bytes,3,opt,name=access_level,json=accessLevel,proto3" json:"access_level,omitempty"`
	InheritedTypes []string               `protobuf:"bytes,4,rep,name=inherited_types,json=inheritedTypes,proto3" json:"inherited_types,omitempty"`
	Members        []*IndexMemberInfo     `protobuf:"bytes,5,rep,name=members,proto3" json:"members,omitempty"`
	Line           int32                  `protobuf:"varint,6,opt,name=line,proto3" json:"line,omitempty"`
	Column         int32                  `protobuf:"varint,7,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IndexTypeInfo) Reset() {
	*x = IndexTypeInfo{}
	mi := &file_analysis_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexTypeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexTypeInfo) ProtoMessage() {}

func (x *IndexTypeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexTypeInfo.ProtoReflect.Descriptor instead.
func (*IndexTypeInfo) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{8}
}

func (x *IndexTypeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IndexTypeInfo) GetKind() TypeKind {
	if x != nil {
		return x.Kind
	}
	return TypeKind_TYPE_KIND_UNKNOWN
}

func (x *IndexTypeInfo) GetAccessLevel() string {
	if x != nil {
		return x.AccessLevel
	}
	return ""
}

func (x *IndexTypeInfo) GetInheritedTypes() []string {
	if x != nil {
		return x.InheritedTypes
	}
	return nil
}

func (x *IndexTypeInfo) GetMembers() []*IndexMemberInfo {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *IndexTypeInfo) GetLine() int32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *IndexTypeInfo) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

type IndexFileData struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	FilePath            string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Types               []*IndexTypeInfo       `protobuf:"bytes,2,rep,name=types,proto3" json:"types,omitempty"`
	ReferencedTypeNames []string               `protobuf:"bytes,3,rep,name=referenced_type_names,json=referencedTypeNames,proto3" json:"referenced_type_names,omitempty"`
	DefinedTypeNames    []string               `protobuf:"bytes,4,rep,name=defined_type_names,json=definedTypeNames,proto3" json:"defined_type_names,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *IndexFileData) Reset() {
	*x = IndexFileData{}
	mi := &file_analysis_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexFileData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexFileData) ProtoMessage() {}

func (x *IndexFileData) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexFileData.ProtoReflect.Descriptor instead.
func (*IndexFileData) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{9}
}

func (x *IndexFileData) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *IndexFileData) GetTypes() []*IndexTypeInfo {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *IndexFileData) GetReferencedTypeNames() []string {
	if x != nil {
		return x.ReferencedTypeNames
	}
	return nil
}

func (x *IndexFileData) GetDefinedTypeNames() []string {
	if x != nil {
		return x.DefinedTypeNames
	}
	return nil
}

type IndexStoreResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*IndexFileData       `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	TypeFileMap   map[string]string      `protobuf:"bytes,2,rep,name=type_file_map,json=typeFileMap,proto3" json:"type_file_map,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IndexStoreResult) Reset() {
	*x = IndexStoreResult{}
	mi := &file_analysis_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndexStoreResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndexStoreResult) ProtoMessage() {}

func (x *IndexStoreResult) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndexStoreResult.ProtoReflect.Descriptor instead.
func (*IndexStoreResult) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{10}
}

func (x *IndexStoreResult) GetFiles() []*IndexFileData {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *IndexStoreResult) GetTypeFileMap() map[string]string {
	if x != nil {
		return x.TypeFileMap
	}
	return nil
}

var File_analysis_proto protoreflect.FileDescriptor

const file_analysis_proto_rawDesc = "" +
	"\n" +
	"\x0eanalysis.proto\x12\faxe.analysis\"t\n" +
	"\fPropertyInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\ttype_expr\x18\x02 \x01(\tR\btypeExpr\x12\x1b\n" +
	"\tbody_line\x18\x03 \x01(\x05R\bbodyLine\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\"\x8f\x01\n" +
	"\n" +
	"MethodInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bselector\x18\x02 \x01(\tR\bselector\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\x12\x1b\n" +
	"\tbody_line\x18\x04 \x01(\x05R\bbodyLine\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\"\x86\x02\n" +
	"\bTypeInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12*\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x16.axe.analysis.TypeKindR\x04kind\x12!\n" +
	"\faccess_level\x18\x03 \x01(\tR\vaccessLevel\x12'\n" +
	"\x0finherited_types\x18\x04 \x03(\tR\x0einheritedTypes\x12:\n" +
	"\n" +
	"properties\x18\x05 \x03(\v2\x1a.axe.analysis.PropertyInfoR\n" +
	"properties\x122\n" +
	"\amethods\x18\x06 \x03(\v2\x18.axe.analysis.MethodInfoR\amethods\"[\n" +
	"\fPreviewBlock\x12\x1d\n" +
	"\n" +
	"start_line\x18\x01 \x01(\x05R\tstartLine\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\"\x93\x02\n" +
	"\fMemberSource\x12\x1b\n" +
	"\ttype_name\x18\x01 \x01(\tR\btypeName\x12\x12\n" +
	"\x04line\x18\x02 \x01(\x05R\x04line\x122\n" +
	"\x04kind\x18\x03 \x01(\x0e2\x1e.axe.analysis.MemberSourceKindR\x04kind\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1b\n" +
	"\ttype_expr\x18\x05 \x01(\tR\btypeExpr\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\tR\tsignature\x12\x1a\n" +
	"\bselector\x18\a \x01(\tR\bselector\x12\x1b\n" +
	"\tbody_line\x18\b \x01(\x05R\bbodyLine\x12\x16\n" +
	"\x06source\x18\t \x01(\tR\x06source\"\xd9\x01\n" +
	"\vParseResult\x12\x18\n" +
	"\aimports\x18\x02 \x03(\tR\aimports\x126\n" +
	"\bpreviews\x18\x03 \x03(\v2\x1a.axe.analysis.PreviewBlockR\bpreviews\x12#\n" +
	"\rskeleton_hash\x18\x04 \x01(\tR\fskeletonHash\x12A\n" +
	"\x0emember_sources\x18\a \x03(\v2\x1a.axe.analysis.MemberSourceR\rmemberSourcesJ\x04\b\x01\x10\x02J\x04\b\x05\x10\x06J\x04\b\x06\x10\a\"\x83\x01\n" +
	"\vTypeFileMap\x12:\n" +
	"\x05types\x18\x01 \x03(\v2$.axe.analysis.TypeFileMap.TypesEntryR\x05types\x1a8\n" +
	"\n" +
	"TypesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc3\x01\n" +
	"\x0fIndexMemberInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12,\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x18.axe.analysis.MemberKindR\x04kind\x12!\n" +
	"\faccess_level\x18\x03 \x01(\tR\vaccessLevel\x12\x12\n" +
	"\x04line\x18\x04 \x01(\x05R\x04line\x12\x16\n" +
	"\x06column\x18\x05 \x01(\x05R\x06column\x12\x1f\n" +
	"\vis_computed\x18\x06 \x01(\bR\n" +
	"isComputed\"\x80\x02\n" +
	"\rIndexTypeInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12*\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x16.axe.analysis.TypeKindR\x04kind\x12!\n" +
	"\faccess_level\x18\x03 \x01(\tR\vaccessLevel\x12'\n" +
	"\x0finherited_types\x18\x04 \x03(\tR\x0einheritedTypes\x127\n" +
	"\amembers\x18\x05 \x03(\v2\x1d.axe.analysis.IndexMemberInfoR\amembers\x12\x12\n" +
	"\x04line\x18\x06 \x01(\x05R\x04line\x12\x16\n" +
	"\x06column\x18\a \x01(\x05R\x06column\"\xc1\x01\n" +
	"\rIndexFileData\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x121\n" +
	"\x05types\x18\x02 \x03(\v2\x1b.axe.analysis.IndexTypeInfoR\x05types\x122\n" +
	"\x15referenced_type_names\x18\x03 \x03(\tR\x13referencedTypeNames\x12,\n" +
	"\x12defined_type_names\x18\x04 \x03(\tR\x10definedTypeNames\"\xda\x01\n" +
	"\x10IndexStoreResult\x121\n" +
	"\x05files\x18\x01 \x03(\v2\x1b.axe.analysis.IndexFileDataR\x05files\x12S\n" +
	"\rtype_file_map\x18\x02 \x03(\v2/.axe.analysis.IndexStoreResult.TypeFileMapEntryR\vtypeFileMap\x1a>\n" +
	"\x10TypeFileMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*u\n" +
	"\bTypeKind\x12\x15\n" +
	"\x11TYPE_KIND_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10TYPE_KIND_STRUCT\x10\x01\x12\x13\n" +
	"\x0fTYPE_KIND_CLASS\x10\x02\x12\x12\n" +
	"\x0eTYPE_KIND_ENUM\x10\x03\x12\x13\n" +
	"\x0fTYPE_KIND_ACTOR\x10\x04*r\n" +
	"\x10MemberSourceKind\x12\x1e\n" +
	"\x1aMEMBER_SOURCE_KIND_UNKNOWN\x10\x00\x12\x1f\n" +
	"\x1bMEMBER_SOURCE_KIND_PROPERTY\x10\x01\x12\x1d\n" +
	"\x19MEMBER_SOURCE_KIND_METHOD\x10\x02*\xc6\x01\n" +
	"\n" +
	"MemberKind\x12\x17\n" +
	"\x13MEMBER_KIND_UNKNOWN\x10\x00\x12!\n" +
	"\x1dMEMBER_KIND_INSTANCE_PROPERTY\x10\x01\x12\x1f\n" +
	"\x1bMEMBER_KIND_INSTANCE_METHOD\x10\x02\x12\x1f\n" +
	"\x1bMEMBER_KIND_STATIC_PROPERTY\x10\x03\x12\x1d\n" +
	"\x19MEMBER_KIND_STATIC_METHOD\x10\x04\x12\x1b\n" +
	"\x17MEMBER_KIND_CONSTRUCTOR\x10\x05B7Z5github.com/k-kohey/axe/internal/preview/analysisprotob\x06proto3"

var (
	file_analysis_proto_rawDescOnce sync.Once
	file_analysis_proto_rawDescData []byte
)

func file_analysis_proto_rawDescGZIP() []byte {
	file_analysis_proto_rawDescOnce.Do(func() {
		file_analysis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analysis_proto_rawDesc), len(file_analysis_proto_rawDesc)))
	})
	return file_analysis_proto_rawDescData
}

var file_analysis_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_analysis_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_analysis_proto_goTypes = []any{
	(TypeKind)(0),            // 0: axe.analysis.TypeKind
	(MemberSourceKind)(0),    // 1: axe.analysis.MemberSourceKind
	(MemberKind)(0),          // 2: axe.analysis.MemberKind
	(*PropertyInfo)(nil),     // 3: axe.analysis.PropertyInfo
	(*MethodInfo)(nil),       // 4: axe.analysis.MethodInfo
	(*TypeInfo)(nil),         // 5: axe.analysis.TypeInfo
	(*PreviewBlock)(nil),     // 6: axe.analysis.PreviewBlock
	(*MemberSource)(nil),     // 7: axe.analysis.MemberSource
	(*ParseResult)(nil),      // 8: axe.analysis.ParseResult
	(*TypeFileMap)(nil),      // 9: axe.analysis.TypeFileMap
	(*IndexMemberInfo)(nil),  // 10: axe.analysis.IndexMemberInfo
	(*IndexTypeInfo)(nil),    // 11: axe.analysis.IndexTypeInfo
	(*IndexFileData)(nil),    // 12: axe.analysis.IndexFileData
	(*IndexStoreResult)(nil), // 13: axe.analysis.IndexStoreResult
	nil,                      // 14: axe.analysis.TypeFileMap.TypesEntry
	nil,                      // 15: axe.analysis.IndexStoreResult.TypeFileMapEntry
}
var file_analysis_proto_depIdxs = []int32{
	0,  // 0: axe.analysis.TypeInfo.kind:type_name -> axe.analysis.TypeKind
	3,  // 1: axe.analysis.TypeInfo.properties:type_name -> axe.analysis.PropertyInfo
	4,  // 2: axe.analysis.TypeInfo.methods:type_name -> axe.analysis.MethodInfo
	1,  // 3: axe.analysis.MemberSource.kind:type_name -> axe.analysis.MemberSourceKind
	6,  // 4: axe.analysis.ParseResult.previews:type_name -> axe.analysis.PreviewBlock
	7,  // 5: axe.analysis.ParseResult.member_sources:type_name -> axe.analysis.MemberSource
	14, // 6: axe.analysis.TypeFileMap.types:type_name -> axe.analysis.TypeFileMap.TypesEntry
	2,  // 7: axe.analysis.IndexMemberInfo.kind:type_name -> axe.analysis.MemberKind
	0,  // 8: axe.analysis.IndexTypeInfo.kind:type_name -> axe.analysis.TypeKind
	10, // 9: axe.analysis.IndexTypeInfo.members:type_name -> axe.analysis.IndexMemberInfo
	11, // 10: axe.analysis.IndexFileData.types:type_name -> axe.analysis.IndexTypeInfo
	12, // 11: axe.analysis.IndexStoreResult.files:type_name -> axe.analysis.IndexFileData
	15, // 12: axe.analysis.IndexStoreResult.type_file_map:type_name -> axe.analysis.IndexStoreResult.TypeFileMapEntry
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_analysis_proto_init() }
func file_analysis_proto_init() {
	if File_analysis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analysis_proto_rawDesc), len(file_analysis_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_analysis_proto_goTypes,
		DependencyIndexes: file_analysis_proto_depIdxs,
		EnumInfos:         file_analysis_proto_enumTypes,
		MessageInfos:      file_analysis_proto_msgTypes,
	}.Build()
	File_analysis_proto = out.File
	file_analysis_proto_goTypes = nil
	file_analysis_proto_depIdxs = nil
}
