// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: analysis.proto

package analysisproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TypeKind int32

const (
	TypeKind_TYPE_KIND_UNKNOWN TypeKind = 0
	TypeKind_TYPE_KIND_STRUCT  TypeKind = 1
	TypeKind_TYPE_KIND_CLASS   TypeKind = 2
	TypeKind_TYPE_KIND_ENUM    TypeKind = 3
	TypeKind_TYPE_KIND_ACTOR   TypeKind = 4
)

// Enum value maps for TypeKind.
var (
	TypeKind_name = map[int32]string{
		0: "TYPE_KIND_UNKNOWN",
		1: "TYPE_KIND_STRUCT",
		2: "TYPE_KIND_CLASS",
		3: "TYPE_KIND_ENUM",
		4: "TYPE_KIND_ACTOR",
	}
	TypeKind_value = map[string]int32{
		"TYPE_KIND_UNKNOWN": 0,
		"TYPE_KIND_STRUCT":  1,
		"TYPE_KIND_CLASS":   2,
		"TYPE_KIND_ENUM":    3,
		"TYPE_KIND_ACTOR":   4,
	}
)

func (x TypeKind) Enum() *TypeKind {
	p := new(TypeKind)
	*p = x
	return p
}

func (x TypeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TypeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_analysis_proto_enumTypes[0].Descriptor()
}

func (TypeKind) Type() protoreflect.EnumType {
	return &file_analysis_proto_enumTypes[0]
}

func (x TypeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TypeKind.Descriptor instead.
func (TypeKind) EnumDescriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{0}
}

type PropertyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TypeExpr      string                 `protobuf:"bytes,2,opt,name=type_expr,json=typeExpr,proto3" json:"type_expr,omitempty"`
	BodyLine      int32                  `protobuf:"varint,3,opt,name=body_line,json=bodyLine,proto3" json:"body_line,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PropertyInfo) Reset() {
	*x = PropertyInfo{}
	mi := &file_analysis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropertyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyInfo) ProtoMessage() {}

func (x *PropertyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyInfo.ProtoReflect.Descriptor instead.
func (*PropertyInfo) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{0}
}

func (x *PropertyInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PropertyInfo) GetTypeExpr() string {
	if x != nil {
		return x.TypeExpr
	}
	return ""
}

func (x *PropertyInfo) GetBodyLine() int32 {
	if x != nil {
		return x.BodyLine
	}
	return 0
}

func (x *PropertyInfo) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type MethodInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Selector      string                 `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"`
	Signature     string                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	BodyLine      int32                  `protobuf:"varint,4,opt,name=body_line,json=bodyLine,proto3" json:"body_line,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MethodInfo) Reset() {
	*x = MethodInfo{}
	mi := &file_analysis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodInfo) ProtoMessage() {}

func (x *MethodInfo) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodInfo.ProtoReflect.Descriptor instead.
func (*MethodInfo) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{1}
}

func (x *MethodInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MethodInfo) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *MethodInfo) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *MethodInfo) GetBodyLine() int32 {
	if x != nil {
		return x.BodyLine
	}
	return 0
}

func (x *MethodInfo) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type TypeInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind           TypeKind               `protobuf:"varint,2,opt,name=kind,proto3,enum=axe.analysis.TypeKind" json:"kind,omitempty"`
	AccessLevel    string                 `protobuf:"bytes,3,opt,name=access_level,json=accessLevel,proto3" json:"access_level,omitempty"`
	InheritedTypes []string               `protobuf:"bytes,4,rep,name=inherited_types,json=inheritedTypes,proto3" json:"inherited_types,omitempty"`
	Properties     []*PropertyInfo        `protobuf:"bytes,5,rep,name=properties,proto3" json:"properties,omitempty"`
	Methods        []*MethodInfo          `protobuf:"bytes,6,rep,name=methods,proto3" json:"methods,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TypeInfo) Reset() {
	*x = TypeInfo{}
	mi := &file_analysis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeInfo) ProtoMessage() {}

func (x *TypeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeInfo.ProtoReflect.Descriptor instead.
func (*TypeInfo) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{2}
}

func (x *TypeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TypeInfo) GetKind() TypeKind {
	if x != nil {
		return x.Kind
	}
	return TypeKind_TYPE_KIND_UNKNOWN
}

func (x *TypeInfo) GetAccessLevel() string {
	if x != nil {
		return x.AccessLevel
	}
	return ""
}

func (x *TypeInfo) GetInheritedTypes() []string {
	if x != nil {
		return x.InheritedTypes
	}
	return nil
}

func (x *TypeInfo) GetProperties() []*PropertyInfo {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *TypeInfo) GetMethods() []*MethodInfo {
	if x != nil {
		return x.Methods
	}
	return nil
}

type PreviewBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartLine     int32                  `protobuf:"varint,1,opt,name=start_line,json=startLine,proto3" json:"start_line,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewBlock) Reset() {
	*x = PreviewBlock{}
	mi := &file_analysis_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewBlock) ProtoMessage() {}

func (x *PreviewBlock) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewBlock.ProtoReflect.Descriptor instead.
func (*PreviewBlock) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{3}
}

func (x *PreviewBlock) GetStartLine() int32 {
	if x != nil {
		return x.StartLine
	}
	return 0
}

func (x *PreviewBlock) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PreviewBlock) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type ParseResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Types           []*TypeInfo            `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	Imports         []string               `protobuf:"bytes,2,rep,name=imports,proto3" json:"imports,omitempty"`
	Previews        []*PreviewBlock        `protobuf:"bytes,3,rep,name=previews,proto3" json:"previews,omitempty"`
	SkeletonHash    string                 `protobuf:"bytes,4,opt,name=skeleton_hash,json=skeletonHash,proto3" json:"skeleton_hash,omitempty"`
	ReferencedTypes []string               `protobuf:"bytes,5,rep,name=referenced_types,json=referencedTypes,proto3" json:"referenced_types,omitempty"`
	DefinedTypes    []string               `protobuf:"bytes,6,rep,name=defined_types,json=definedTypes,proto3" json:"defined_types,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ParseResult) Reset() {
	*x = ParseResult{}
	mi := &file_analysis_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseResult) ProtoMessage() {}

func (x *ParseResult) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseResult.ProtoReflect.Descriptor instead.
func (*ParseResult) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{4}
}

func (x *ParseResult) GetTypes() []*TypeInfo {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *ParseResult) GetImports() []string {
	if x != nil {
		return x.Imports
	}
	return nil
}

func (x *ParseResult) GetPreviews() []*PreviewBlock {
	if x != nil {
		return x.Previews
	}
	return nil
}

func (x *ParseResult) GetSkeletonHash() string {
	if x != nil {
		return x.SkeletonHash
	}
	return ""
}

func (x *ParseResult) GetReferencedTypes() []string {
	if x != nil {
		return x.ReferencedTypes
	}
	return nil
}

func (x *ParseResult) GetDefinedTypes() []string {
	if x != nil {
		return x.DefinedTypes
	}
	return nil
}

type TypeFileMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Types         map[string]string      `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // typeName → filePath
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeFileMap) Reset() {
	*x = TypeFileMap{}
	mi := &file_analysis_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeFileMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeFileMap) ProtoMessage() {}

func (x *TypeFileMap) ProtoReflect() protoreflect.Message {
	mi := &file_analysis_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeFileMap.ProtoReflect.Descriptor instead.
func (*TypeFileMap) Descriptor() ([]byte, []int) {
	return file_analysis_proto_rawDescGZIP(), []int{5}
}

func (x *TypeFileMap) GetTypes() map[string]string {
	if x != nil {
		return x.Types
	}
	return nil
}

var File_analysis_proto protoreflect.FileDescriptor

const file_analysis_proto_rawDesc = "" +
	"\n" +
	"\x0eanalysis.proto\x12\faxe.analysis\"t\n" +
	"\fPropertyInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\ttype_expr\x18\x02 \x01(\tR\btypeExpr\x12\x1b\n" +
	"\tbody_line\x18\x03 \x01(\x05R\bbodyLine\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\"\x8f\x01\n" +
	"\n" +
	"MethodInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bselector\x18\x02 \x01(\tR\bselector\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\tR\tsignature\x12\x1b\n" +
	"\tbody_line\x18\x04 \x01(\x05R\bbodyLine\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\"\x86\x02\n" +
	"\bTypeInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12*\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x16.axe.analysis.TypeKindR\x04kind\x12!\n" +
	"\faccess_level\x18\x03 \x01(\tR\vaccessLevel\x12'\n" +
	"\x0finherited_types\x18\x04 \x03(\tR\x0einheritedTypes\x12:\n" +
	"\n" +
	"properties\x18\x05 \x03(\v2\x1a.axe.analysis.PropertyInfoR\n" +
	"properties\x122\n" +
	"\amethods\x18\x06 \x03(\v2\x18.axe.analysis.MethodInfoR\amethods\"[\n" +
	"\fPreviewBlock\x12\x1d\n" +
	"\n" +
	"start_line\x18\x01 \x01(\x05R\tstartLine\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\"\x82\x02\n" +
	"\vParseResult\x12,\n" +
	"\x05types\x18\x01 \x03(\v2\x16.axe.analysis.TypeInfoR\x05types\x12\x18\n" +
	"\aimports\x18\x02 \x03(\tR\aimports\x126\n" +
	"\bpreviews\x18\x03 \x03(\v2\x1a.axe.analysis.PreviewBlockR\bpreviews\x12#\n" +
	"\rskeleton_hash\x18\x04 \x01(\tR\fskeletonHash\x12)\n" +
	"\x10referenced_types\x18\x05 \x03(\tR\x0freferencedTypes\x12#\n" +
	"\rdefined_types\x18\x06 \x03(\tR\fdefinedTypes\"\x83\x01\n" +
	"\vTypeFileMap\x12:\n" +
	"\x05types\x18\x01 \x03(\v2$.axe.analysis.TypeFileMap.TypesEntryR\x05types\x1a8\n" +
	"\n" +
	"TypesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*u\n" +
	"\bTypeKind\x12\x15\n" +
	"\x11TYPE_KIND_UNKNOWN\x10\x00\x12\x14\n" +
	"\x10TYPE_KIND_STRUCT\x10\x01\x12\x13\n" +
	"\x0fTYPE_KIND_CLASS\x10\x02\x12\x12\n" +
	"\x0eTYPE_KIND_ENUM\x10\x03\x12\x13\n" +
	"\x0fTYPE_KIND_ACTOR\x10\x04B7Z5github.com/k-kohey/axe/internal/preview/analysisprotob\x06proto3"

var (
	file_analysis_proto_rawDescOnce sync.Once
	file_analysis_proto_rawDescData []byte
)

func file_analysis_proto_rawDescGZIP() []byte {
	file_analysis_proto_rawDescOnce.Do(func() {
		file_analysis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analysis_proto_rawDesc), len(file_analysis_proto_rawDesc)))
	})
	return file_analysis_proto_rawDescData
}

var file_analysis_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_analysis_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_analysis_proto_goTypes = []any{
	(TypeKind)(0),        // 0: axe.analysis.TypeKind
	(*PropertyInfo)(nil), // 1: axe.analysis.PropertyInfo
	(*MethodInfo)(nil),   // 2: axe.analysis.MethodInfo
	(*TypeInfo)(nil),     // 3: axe.analysis.TypeInfo
	(*PreviewBlock)(nil), // 4: axe.analysis.PreviewBlock
	(*ParseResult)(nil),  // 5: axe.analysis.ParseResult
	(*TypeFileMap)(nil),  // 6: axe.analysis.TypeFileMap
	nil,                  // 7: axe.analysis.TypeFileMap.TypesEntry
}
var file_analysis_proto_depIdxs = []int32{
	0, // 0: axe.analysis.TypeInfo.kind:type_name -> axe.analysis.TypeKind
	1, // 1: axe.analysis.TypeInfo.properties:type_name -> axe.analysis.PropertyInfo
	2, // 2: axe.analysis.TypeInfo.methods:type_name -> axe.analysis.MethodInfo
	3, // 3: axe.analysis.ParseResult.types:type_name -> axe.analysis.TypeInfo
	4, // 4: axe.analysis.ParseResult.previews:type_name -> axe.analysis.PreviewBlock
	7, // 5: axe.analysis.TypeFileMap.types:type_name -> axe.analysis.TypeFileMap.TypesEntry
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_analysis_proto_init() }
func file_analysis_proto_init() {
	if File_analysis_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analysis_proto_rawDesc), len(file_analysis_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_analysis_proto_goTypes,
		DependencyIndexes: file_analysis_proto_depIdxs,
		EnumInfos:         file_analysis_proto_enumTypes,
		MessageInfos:      file_analysis_proto_msgTypes,
	}.Build()
	File_analysis_proto = out.File
	file_analysis_proto_goTypes = nil
	file_analysis_proto_depIdxs = nil
}
