// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/simulator/v1/simulator.proto

package simulatorv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SimulatorService_Health_FullMethodName                  = "/axe.simulator.v1.SimulatorService/Health"
	SimulatorService_ListDevices_FullMethodName             = "/axe.simulator.v1.SimulatorService/ListDevices"
	SimulatorService_ListManagedDevices_FullMethodName      = "/axe.simulator.v1.SimulatorService/ListManagedDevices"
	SimulatorService_AddManagedDevice_FullMethodName        = "/axe.simulator.v1.SimulatorService/AddManagedDevice"
	SimulatorService_RemoveManagedDevice_FullMethodName     = "/axe.simulator.v1.SimulatorService/RemoveManagedDevice"
	SimulatorService_SetDefaultManagedDevice_FullMethodName = "/axe.simulator.v1.SimulatorService/SetDefaultManagedDevice"
	SimulatorService_CreateSession_FullMethodName           = "/axe.simulator.v1.SimulatorService/CreateSession"
	SimulatorService_ListSessions_FullMethodName            = "/axe.simulator.v1.SimulatorService/ListSessions"
	SimulatorService_GetSession_FullMethodName              = "/axe.simulator.v1.SimulatorService/GetSession"
	SimulatorService_StopSession_FullMethodName             = "/axe.simulator.v1.SimulatorService/StopSession"
	SimulatorService_InstallApp_FullMethodName              = "/axe.simulator.v1.SimulatorService/InstallApp"
	SimulatorService_LaunchApp_FullMethodName               = "/axe.simulator.v1.SimulatorService/LaunchApp"
	SimulatorService_TerminateApp_FullMethodName            = "/axe.simulator.v1.SimulatorService/TerminateApp"
	SimulatorService_SendInput_FullMethodName               = "/axe.simulator.v1.SimulatorService/SendInput"
	SimulatorService_WatchEvents_FullMethodName             = "/axe.simulator.v1.SimulatorService/WatchEvents"
	SimulatorService_WatchVideo_FullMethodName              = "/axe.simulator.v1.SimulatorService/WatchVideo"
)

// SimulatorServiceClient is the client API for SimulatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SimulatorServiceClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error)
	ListManagedDevices(ctx context.Context, in *ListManagedDevicesRequest, opts ...grpc.CallOption) (*ListManagedDevicesResponse, error)
	AddManagedDevice(ctx context.Context, in *AddManagedDeviceRequest, opts ...grpc.CallOption) (*AddManagedDeviceResponse, error)
	RemoveManagedDevice(ctx context.Context, in *RemoveManagedDeviceRequest, opts ...grpc.CallOption) (*RemoveManagedDeviceResponse, error)
	SetDefaultManagedDevice(ctx context.Context, in *SetDefaultManagedDeviceRequest, opts ...grpc.CallOption) (*SetDefaultManagedDeviceResponse, error)
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error)
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*Session, error)
	StopSession(ctx context.Context, in *StopSessionRequest, opts ...grpc.CallOption) (*StopSessionResponse, error)
	InstallApp(ctx context.Context, in *InstallAppRequest, opts ...grpc.CallOption) (*InstallAppResponse, error)
	LaunchApp(ctx context.Context, in *LaunchAppRequest, opts ...grpc.CallOption) (*LaunchAppResponse, error)
	TerminateApp(ctx context.Context, in *TerminateAppRequest, opts ...grpc.CallOption) (*TerminateAppResponse, error)
	SendInput(ctx context.Context, in *SendInputRequest, opts ...grpc.CallOption) (*SendInputResponse, error)
	WatchEvents(ctx context.Context, in *WatchEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error)
	WatchVideo(ctx context.Context, in *WatchVideoRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[VideoFrame], error)
}

type simulatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSimulatorServiceClient(cc grpc.ClientConnInterface) SimulatorServiceClient {
	return &simulatorServiceClient{cc}
}

func (c *simulatorServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, SimulatorService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulatorServiceClient) ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDevicesResponse)
	err := c.cc.Invoke(ctx, SimulatorService_ListDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulatorServiceClient) ListManagedDevices(ctx context.Context, in *ListManagedDevicesRequest, opts ...grpc.CallOption) (*ListManagedDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListManagedDevicesResponse)
	err := c.cc.Invoke(ctx, SimulatorService_ListManagedDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulatorServiceClient) AddManagedDevice(ctx context.Context, in *AddManagedDeviceRequest, opts ...grpc.CallOption) (*AddManagedDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddManagedDeviceResponse)
	err := c.cc.Invoke(ctx, SimulatorService_AddManagedDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulatorServiceClient) RemoveManagedDevice(ctx context.Context, in *RemoveManagedDeviceRequest, opts ...grpc.CallOption) (*RemoveManagedDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveManagedDeviceResponse)
	err := c.cc.Invoke(ctx, SimulatorService_RemoveManagedDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulatorServiceClient) SetDefaultManagedDevice(ctx context.Context, in *SetDefaultManagedDeviceRequest, opts ...grpc.CallOption) (*SetDefaultManagedDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetDefaultManagedDeviceResponse)
	err := c.cc.Invoke(ctx, SimulatorService_SetDefaultManagedDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulatorServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSessionResponse)
	err := c.cc.Invoke(ctx, SimulatorService_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulatorServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, SimulatorService_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulatorServiceClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*Session, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Session)
	err := c.cc.Invoke(ctx, SimulatorService_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulatorServiceClient) StopSession(ctx context.Context, in *StopSessionRequest, opts ...grpc.CallOption) (*StopSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopSessionResponse)
	err := c.cc.Invoke(ctx, SimulatorService_StopSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulatorServiceClient) InstallApp(ctx context.Context, in *InstallAppRequest, opts ...grpc.CallOption) (*InstallAppResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstallAppResponse)
	err := c.cc.Invoke(ctx, SimulatorService_InstallApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulatorServiceClient) LaunchApp(ctx context.Context, in *LaunchAppRequest, opts ...grpc.CallOption) (*LaunchAppResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LaunchAppResponse)
	err := c.cc.Invoke(ctx, SimulatorService_LaunchApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulatorServiceClient) TerminateApp(ctx context.Context, in *TerminateAppRequest, opts ...grpc.CallOption) (*TerminateAppResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TerminateAppResponse)
	err := c.cc.Invoke(ctx, SimulatorService_TerminateApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulatorServiceClient) SendInput(ctx context.Context, in *SendInputRequest, opts ...grpc.CallOption) (*SendInputResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendInputResponse)
	err := c.cc.Invoke(ctx, SimulatorService_SendInput_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *simulatorServiceClient) WatchEvents(ctx context.Context, in *WatchEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Event], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SimulatorService_ServiceDesc.Streams[0], SimulatorService_WatchEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchEventsRequest, Event]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SimulatorService_WatchEventsClient = grpc.ServerStreamingClient[Event]

func (c *simulatorServiceClient) WatchVideo(ctx context.Context, in *WatchVideoRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[VideoFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SimulatorService_ServiceDesc.Streams[1], SimulatorService_WatchVideo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchVideoRequest, VideoFrame]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SimulatorService_WatchVideoClient = grpc.ServerStreamingClient[VideoFrame]

// SimulatorServiceServer is the server API for SimulatorService service.
// All implementations must embed UnimplementedSimulatorServiceServer
// for forward compatibility.
type SimulatorServiceServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error)
	ListManagedDevices(context.Context, *ListManagedDevicesRequest) (*ListManagedDevicesResponse, error)
	AddManagedDevice(context.Context, *AddManagedDeviceRequest) (*AddManagedDeviceResponse, error)
	RemoveManagedDevice(context.Context, *RemoveManagedDeviceRequest) (*RemoveManagedDeviceResponse, error)
	SetDefaultManagedDevice(context.Context, *SetDefaultManagedDeviceRequest) (*SetDefaultManagedDeviceResponse, error)
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error)
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	GetSession(context.Context, *GetSessionRequest) (*Session, error)
	StopSession(context.Context, *StopSessionRequest) (*StopSessionResponse, error)
	InstallApp(context.Context, *InstallAppRequest) (*InstallAppResponse, error)
	LaunchApp(context.Context, *LaunchAppRequest) (*LaunchAppResponse, error)
	TerminateApp(context.Context, *TerminateAppRequest) (*TerminateAppResponse, error)
	SendInput(context.Context, *SendInputRequest) (*SendInputResponse, error)
	WatchEvents(*WatchEventsRequest, grpc.ServerStreamingServer[Event]) error
	WatchVideo(*WatchVideoRequest, grpc.ServerStreamingServer[VideoFrame]) error
	mustEmbedUnimplementedSimulatorServiceServer()
}

// UnimplementedSimulatorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSimulatorServiceServer struct{}

func (UnimplementedSimulatorServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedSimulatorServiceServer) ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDevices not implemented")
}
func (UnimplementedSimulatorServiceServer) ListManagedDevices(context.Context, *ListManagedDevicesRequest) (*ListManagedDevicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListManagedDevices not implemented")
}
func (UnimplementedSimulatorServiceServer) AddManagedDevice(context.Context, *AddManagedDeviceRequest) (*AddManagedDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddManagedDevice not implemented")
}
func (UnimplementedSimulatorServiceServer) RemoveManagedDevice(context.Context, *RemoveManagedDeviceRequest) (*RemoveManagedDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveManagedDevice not implemented")
}
func (UnimplementedSimulatorServiceServer) SetDefaultManagedDevice(context.Context, *SetDefaultManagedDeviceRequest) (*SetDefaultManagedDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetDefaultManagedDevice not implemented")
}
func (UnimplementedSimulatorServiceServer) CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedSimulatorServiceServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedSimulatorServiceServer) GetSession(context.Context, *GetSessionRequest) (*Session, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedSimulatorServiceServer) StopSession(context.Context, *StopSessionRequest) (*StopSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopSession not implemented")
}
func (UnimplementedSimulatorServiceServer) InstallApp(context.Context, *InstallAppRequest) (*InstallAppResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InstallApp not implemented")
}
func (UnimplementedSimulatorServiceServer) LaunchApp(context.Context, *LaunchAppRequest) (*LaunchAppResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LaunchApp not implemented")
}
func (UnimplementedSimulatorServiceServer) TerminateApp(context.Context, *TerminateAppRequest) (*TerminateAppResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TerminateApp not implemented")
}
func (UnimplementedSimulatorServiceServer) SendInput(context.Context, *SendInputRequest) (*SendInputResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendInput not implemented")
}
func (UnimplementedSimulatorServiceServer) WatchEvents(*WatchEventsRequest, grpc.ServerStreamingServer[Event]) error {
	return status.Error(codes.Unimplemented, "method WatchEvents not implemented")
}
func (UnimplementedSimulatorServiceServer) WatchVideo(*WatchVideoRequest, grpc.ServerStreamingServer[VideoFrame]) error {
	return status.Error(codes.Unimplemented, "method WatchVideo not implemented")
}
func (UnimplementedSimulatorServiceServer) mustEmbedUnimplementedSimulatorServiceServer() {}
func (UnimplementedSimulatorServiceServer) testEmbeddedByValue()                          {}

// UnsafeSimulatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SimulatorServiceServer will
// result in compilation errors.
type UnsafeSimulatorServiceServer interface {
	mustEmbedUnimplementedSimulatorServiceServer()
}

func RegisterSimulatorServiceServer(s grpc.ServiceRegistrar, srv SimulatorServiceServer) {
	// If the following call panics, it indicates UnimplementedSimulatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SimulatorService_ServiceDesc, srv)
}

func _SimulatorService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulatorServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulatorService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulatorServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulatorService_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulatorServiceServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulatorService_ListDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulatorServiceServer).ListDevices(ctx, req.(*ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulatorService_ListManagedDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListManagedDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulatorServiceServer).ListManagedDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulatorService_ListManagedDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulatorServiceServer).ListManagedDevices(ctx, req.(*ListManagedDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulatorService_AddManagedDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddManagedDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulatorServiceServer).AddManagedDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulatorService_AddManagedDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulatorServiceServer).AddManagedDevice(ctx, req.(*AddManagedDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulatorService_RemoveManagedDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveManagedDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulatorServiceServer).RemoveManagedDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulatorService_RemoveManagedDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulatorServiceServer).RemoveManagedDevice(ctx, req.(*RemoveManagedDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulatorService_SetDefaultManagedDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDefaultManagedDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulatorServiceServer).SetDefaultManagedDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulatorService_SetDefaultManagedDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulatorServiceServer).SetDefaultManagedDevice(ctx, req.(*SetDefaultManagedDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulatorService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulatorServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulatorService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulatorServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulatorService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulatorServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulatorService_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulatorServiceServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulatorService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulatorServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulatorService_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulatorServiceServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulatorService_StopSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulatorServiceServer).StopSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulatorService_StopSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulatorServiceServer).StopSession(ctx, req.(*StopSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulatorService_InstallApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulatorServiceServer).InstallApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulatorService_InstallApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulatorServiceServer).InstallApp(ctx, req.(*InstallAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulatorService_LaunchApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LaunchAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulatorServiceServer).LaunchApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulatorService_LaunchApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulatorServiceServer).LaunchApp(ctx, req.(*LaunchAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulatorService_TerminateApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulatorServiceServer).TerminateApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulatorService_TerminateApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulatorServiceServer).TerminateApp(ctx, req.(*TerminateAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulatorService_SendInput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendInputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulatorServiceServer).SendInput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SimulatorService_SendInput_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulatorServiceServer).SendInput(ctx, req.(*SendInputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SimulatorService_WatchEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SimulatorServiceServer).WatchEvents(m, &grpc.GenericServerStream[WatchEventsRequest, Event]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SimulatorService_WatchEventsServer = grpc.ServerStreamingServer[Event]

func _SimulatorService_WatchVideo_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchVideoRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SimulatorServiceServer).WatchVideo(m, &grpc.GenericServerStream[WatchVideoRequest, VideoFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SimulatorService_WatchVideoServer = grpc.ServerStreamingServer[VideoFrame]

// SimulatorService_ServiceDesc is the grpc.ServiceDesc for SimulatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SimulatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "axe.simulator.v1.SimulatorService",
	HandlerType: (*SimulatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _SimulatorService_Health_Handler,
		},
		{
			MethodName: "ListDevices",
			Handler:    _SimulatorService_ListDevices_Handler,
		},
		{
			MethodName: "ListManagedDevices",
			Handler:    _SimulatorService_ListManagedDevices_Handler,
		},
		{
			MethodName: "AddManagedDevice",
			Handler:    _SimulatorService_AddManagedDevice_Handler,
		},
		{
			MethodName: "RemoveManagedDevice",
			Handler:    _SimulatorService_RemoveManagedDevice_Handler,
		},
		{
			MethodName: "SetDefaultManagedDevice",
			Handler:    _SimulatorService_SetDefaultManagedDevice_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _SimulatorService_CreateSession_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _SimulatorService_ListSessions_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _SimulatorService_GetSession_Handler,
		},
		{
			MethodName: "StopSession",
			Handler:    _SimulatorService_StopSession_Handler,
		},
		{
			MethodName: "InstallApp",
			Handler:    _SimulatorService_InstallApp_Handler,
		},
		{
			MethodName: "LaunchApp",
			Handler:    _SimulatorService_LaunchApp_Handler,
		},
		{
			MethodName: "TerminateApp",
			Handler:    _SimulatorService_TerminateApp_Handler,
		},
		{
			MethodName: "SendInput",
			Handler:    _SimulatorService_SendInput_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchEvents",
			Handler:       _SimulatorService_WatchEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchVideo",
			Handler:       _SimulatorService_WatchVideo_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/simulator/v1/simulator.proto",
}
