// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/simulator/v1/simulator.proto

package simulatorv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionState int32

const (
	SessionState_SESSION_STATE_UNSPECIFIED SessionState = 0
	SessionState_SESSION_STATE_STARTING    SessionState = 1
	SessionState_SESSION_STATE_RUNNING     SessionState = 2
	SessionState_SESSION_STATE_STOPPED     SessionState = 3
	SessionState_SESSION_STATE_FAILED      SessionState = 4
)

// Enum value maps for SessionState.
var (
	SessionState_name = map[int32]string{
		0: "SESSION_STATE_UNSPECIFIED",
		1: "SESSION_STATE_STARTING",
		2: "SESSION_STATE_RUNNING",
		3: "SESSION_STATE_STOPPED",
		4: "SESSION_STATE_FAILED",
	}
	SessionState_value = map[string]int32{
		"SESSION_STATE_UNSPECIFIED": 0,
		"SESSION_STATE_STARTING":    1,
		"SESSION_STATE_RUNNING":     2,
		"SESSION_STATE_STOPPED":     3,
		"SESSION_STATE_FAILED":      4,
	}
)

func (x SessionState) Enum() *SessionState {
	p := new(SessionState)
	*p = x
	return p
}

func (x SessionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_simulator_v1_simulator_proto_enumTypes[0].Descriptor()
}

func (SessionState) Type() protoreflect.EnumType {
	return &file_proto_simulator_v1_simulator_proto_enumTypes[0]
}

func (x SessionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionState.Descriptor instead.
func (SessionState) EnumDescriptor() ([]byte, []int) {
	return file_proto_simulator_v1_simulator_proto_rawDescGZIP(), []int{0}
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_simulator_v1_simulator_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_simulator_v1_simulator_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ListDevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_proto_simulator_v1_simulator_proto_rawDescGZIP(), []int{2}
}

type ListDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceTypes   []*DeviceType          `protobuf:"bytes,1,rep,name=device_types,json=deviceTypes,proto3" json:"device_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_proto_simulator_v1_simulator_proto_rawDescGZIP(), []int{3}
}

func (x *ListDevicesResponse) GetDeviceTypes() []*DeviceType {
	if x != nil {
		return x.DeviceTypes
	}
	return nil
}

type DeviceType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Runtimes      []*Runtime             `protobuf:"bytes,3,rep,name=runtimes,proto3" json:"runtimes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceType) Reset() {
	*x = DeviceType{}
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceType) ProtoMessage() {}

func (x *DeviceType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceType.ProtoReflect.Descriptor instead.
func (*DeviceType) Descriptor() ([]byte, []int) {
	return file_proto_simulator_v1_simulator_proto_rawDescGZIP(), []int{4}
}

func (x *DeviceType) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *DeviceType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeviceType) GetRuntimes() []*Runtime {
	if x != nil {
		return x.Runtimes
	}
	return nil
}

type Runtime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Identifier    string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Runtime) Reset() {
	*x = Runtime{}
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Runtime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Runtime) ProtoMessage() {}

func (x *Runtime) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Runtime.ProtoReflect.Descriptor instead.
func (*Runtime) Descriptor() ([]byte, []int) {
	return file_proto_simulator_v1_simulator_proto_rawDescGZIP(), []int{5}
}

func (x *Runtime) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *Runtime) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateSessionRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	DeviceType string                 `protobuf:"bytes,1,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	Runtime    string                 `protobuf:"bytes,2,opt,name=runtime,proto3" json:"runtime,omitempty"`
	// Types that are valid to be assigned to LaunchTarget:
	//
	//	*CreateSessionRequest_AppBundle
	//	*CreateSessionRequest_InstalledApp
	LaunchTarget  isCreateSessionRequest_LaunchTarget `protobuf_oneof:"launch_target"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_simulator_v1_simulator_proto_rawDescGZIP(), []int{6}
}

func (x *CreateSessionRequest) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *CreateSessionRequest) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *CreateSessionRequest) GetLaunchTarget() isCreateSessionRequest_LaunchTarget {
	if x != nil {
		return x.LaunchTarget
	}
	return nil
}

func (x *CreateSessionRequest) GetAppBundle() *AppBundle {
	if x != nil {
		if x, ok := x.LaunchTarget.(*CreateSessionRequest_AppBundle); ok {
			return x.AppBundle
		}
	}
	return nil
}

func (x *CreateSessionRequest) GetInstalledApp() *InstalledApp {
	if x != nil {
		if x, ok := x.LaunchTarget.(*CreateSessionRequest_InstalledApp); ok {
			return x.InstalledApp
		}
	}
	return nil
}

type isCreateSessionRequest_LaunchTarget interface {
	isCreateSessionRequest_LaunchTarget()
}

type CreateSessionRequest_AppBundle struct {
	AppBundle *AppBundle `protobuf:"bytes,10,opt,name=app_bundle,json=appBundle,proto3,oneof"`
}

type CreateSessionRequest_InstalledApp struct {
	InstalledApp *InstalledApp `protobuf:"bytes,11,opt,name=installed_app,json=installedApp,proto3,oneof"`
}

func (*CreateSessionRequest_AppBundle) isCreateSessionRequest_LaunchTarget() {}

func (*CreateSessionRequest_InstalledApp) isCreateSessionRequest_LaunchTarget() {}

type AppBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	BundleId      string                 `protobuf:"bytes,2,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppBundle) Reset() {
	*x = AppBundle{}
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppBundle) ProtoMessage() {}

func (x *AppBundle) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppBundle.ProtoReflect.Descriptor instead.
func (*AppBundle) Descriptor() ([]byte, []int) {
	return file_proto_simulator_v1_simulator_proto_rawDescGZIP(), []int{7}
}

func (x *AppBundle) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *AppBundle) GetBundleId() string {
	if x != nil {
		return x.BundleId
	}
	return ""
}

type InstalledApp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BundleId      string                 `protobuf:"bytes,1,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstalledApp) Reset() {
	*x = InstalledApp{}
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstalledApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstalledApp) ProtoMessage() {}

func (x *InstalledApp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstalledApp.ProtoReflect.Descriptor instead.
func (*InstalledApp) Descriptor() ([]byte, []int) {
	return file_proto_simulator_v1_simulator_proto_rawDescGZIP(), []int{8}
}

func (x *InstalledApp) GetBundleId() string {
	if x != nil {
		return x.BundleId
	}
	return ""
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_simulator_v1_simulator_proto_rawDescGZIP(), []int{9}
}

func (x *CreateSessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_simulator_v1_simulator_proto_rawDescGZIP(), []int{10}
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type StopSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSessionRequest) Reset() {
	*x = StopSessionRequest{}
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSessionRequest) ProtoMessage() {}

func (x *StopSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSessionRequest.ProtoReflect.Descriptor instead.
func (*StopSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_simulator_v1_simulator_proto_rawDescGZIP(), []int{11}
}

func (x *StopSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type StopSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopSessionResponse) Reset() {
	*x = StopSessionResponse{}
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopSessionResponse) ProtoMessage() {}

func (x *StopSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopSessionResponse.ProtoReflect.Descriptor instead.
func (*StopSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_simulator_v1_simulator_proto_rawDescGZIP(), []int{12}
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	DeviceUdid    string                 `protobuf:"bytes,2,opt,name=device_udid,json=deviceUdid,proto3" json:"device_udid,omitempty"`
	DeviceType    string                 `protobuf:"bytes,3,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	Runtime       string                 `protobuf:"bytes,4,opt,name=runtime,proto3" json:"runtime,omitempty"`
	State         SessionState           `protobuf:"varint,5,opt,name=state,proto3,enum=axe.simulator.v1.SessionState" json:"state,omitempty"`
	BundleId      string                 `protobuf:"bytes,6,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	ScreenWidth   int32                  `protobuf:"varint,7,opt,name=screen_width,json=screenWidth,proto3" json:"screen_width,omitempty"`
	ScreenHeight  int32                  `protobuf:"varint,8,opt,name=screen_height,json=screenHeight,proto3" json:"screen_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_proto_simulator_v1_simulator_proto_rawDescGZIP(), []int{13}
}

func (x *Session) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Session) GetDeviceUdid() string {
	if x != nil {
		return x.DeviceUdid
	}
	return ""
}

func (x *Session) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *Session) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *Session) GetState() SessionState {
	if x != nil {
		return x.State
	}
	return SessionState_SESSION_STATE_UNSPECIFIED
}

func (x *Session) GetBundleId() string {
	if x != nil {
		return x.BundleId
	}
	return ""
}

func (x *Session) GetScreenWidth() int32 {
	if x != nil {
		return x.ScreenWidth
	}
	return 0
}

func (x *Session) GetScreenHeight() int32 {
	if x != nil {
		return x.ScreenHeight
	}
	return 0
}

type SendInputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Input         *InputEvent            `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendInputRequest) Reset() {
	*x = SendInputRequest{}
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendInputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendInputRequest) ProtoMessage() {}

func (x *SendInputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendInputRequest.ProtoReflect.Descriptor instead.
func (*SendInputRequest) Descriptor() ([]byte, []int) {
	return file_proto_simulator_v1_simulator_proto_rawDescGZIP(), []int{14}
}

func (x *SendInputRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendInputRequest) GetInput() *InputEvent {
	if x != nil {
		return x.Input
	}
	return nil
}

type SendInputResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendInputResponse) Reset() {
	*x = SendInputResponse{}
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendInputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendInputResponse) ProtoMessage() {}

func (x *SendInputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendInputResponse.ProtoReflect.Descriptor instead.
func (*SendInputResponse) Descriptor() ([]byte, []int) {
	return file_proto_simulator_v1_simulator_proto_rawDescGZIP(), []int{15}
}

type InputEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*InputEvent_TouchDown
	//	*InputEvent_TouchMove
	//	*InputEvent_TouchUp
	//	*InputEvent_Text
	//	*InputEvent_Tap
	//	*InputEvent_Swipe
	Event         isInputEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputEvent) Reset() {
	*x = InputEvent{}
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputEvent) ProtoMessage() {}

func (x *InputEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputEvent.ProtoReflect.Descriptor instead.
func (*InputEvent) Descriptor() ([]byte, []int) {
	return file_proto_simulator_v1_simulator_proto_rawDescGZIP(), []int{16}
}

func (x *InputEvent) GetEvent() isInputEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *InputEvent) GetTouchDown() *TouchEvent {
	if x != nil {
		if x, ok := x.Event.(*InputEvent_TouchDown); ok {
			return x.TouchDown
		}
	}
	return nil
}

func (x *InputEvent) GetTouchMove() *TouchEvent {
	if x != nil {
		if x, ok := x.Event.(*InputEvent_TouchMove); ok {
			return x.TouchMove
		}
	}
	return nil
}

func (x *InputEvent) GetTouchUp() *TouchEvent {
	if x != nil {
		if x, ok := x.Event.(*InputEvent_TouchUp); ok {
			return x.TouchUp
		}
	}
	return nil
}

func (x *InputEvent) GetText() *TextEvent {
	if x != nil {
		if x, ok := x.Event.(*InputEvent_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *InputEvent) GetTap() *TapEvent {
	if x != nil {
		if x, ok := x.Event.(*InputEvent_Tap); ok {
			return x.Tap
		}
	}
	return nil
}

func (x *InputEvent) GetSwipe() *SwipeEvent {
	if x != nil {
		if x, ok := x.Event.(*InputEvent_Swipe); ok {
			return x.Swipe
		}
	}
	return nil
}

type isInputEvent_Event interface {
	isInputEvent_Event()
}

type InputEvent_TouchDown struct {
	TouchDown *TouchEvent `protobuf:"bytes,1,opt,name=touch_down,json=touchDown,proto3,oneof"`
}

type InputEvent_TouchMove struct {
	TouchMove *TouchEvent `protobuf:"bytes,2,opt,name=touch_move,json=touchMove,proto3,oneof"`
}

type InputEvent_TouchUp struct {
	TouchUp *TouchEvent `protobuf:"bytes,3,opt,name=touch_up,json=touchUp,proto3,oneof"`
}

type InputEvent_Text struct {
	Text *TextEvent `protobuf:"bytes,4,opt,name=text,proto3,oneof"`
}

type InputEvent_Tap struct {
	Tap *TapEvent `protobuf:"bytes,5,opt,name=tap,proto3,oneof"`
}

type InputEvent_Swipe struct {
	Swipe *SwipeEvent `protobuf:"bytes,6,opt,name=swipe,proto3,oneof"`
}

func (*InputEvent_TouchDown) isInputEvent_Event() {}

func (*InputEvent_TouchMove) isInputEvent_Event() {}

func (*InputEvent_TouchUp) isInputEvent_Event() {}

func (*InputEvent_Text) isInputEvent_Event() {}

func (*InputEvent_Tap) isInputEvent_Event() {}

func (*InputEvent_Swipe) isInputEvent_Event() {}

type TouchEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TouchEvent) Reset() {
	*x = TouchEvent{}
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TouchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TouchEvent) ProtoMessage() {}

func (x *TouchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TouchEvent.ProtoReflect.Descriptor instead.
func (*TouchEvent) Descriptor() ([]byte, []int) {
	return file_proto_simulator_v1_simulator_proto_rawDescGZIP(), []int{17}
}

func (x *TouchEvent) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *TouchEvent) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type TextEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextEvent) Reset() {
	*x = TextEvent{}
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextEvent) ProtoMessage() {}

func (x *TextEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextEvent.ProtoReflect.Descriptor instead.
func (*TextEvent) Descriptor() ([]byte, []int) {
	return file_proto_simulator_v1_simulator_proto_rawDescGZIP(), []int{18}
}

func (x *TextEvent) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type TapEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TapEvent) Reset() {
	*x = TapEvent{}
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TapEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TapEvent) ProtoMessage() {}

func (x *TapEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TapEvent.ProtoReflect.Descriptor instead.
func (*TapEvent) Descriptor() ([]byte, []int) {
	return file_proto_simulator_v1_simulator_proto_rawDescGZIP(), []int{19}
}

func (x *TapEvent) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *TapEvent) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type SwipeEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StartX          float64                `protobuf:"fixed64,1,opt,name=start_x,json=startX,proto3" json:"start_x,omitempty"`
	StartY          float64                `protobuf:"fixed64,2,opt,name=start_y,json=startY,proto3" json:"start_y,omitempty"`
	EndX            float64                `protobuf:"fixed64,3,opt,name=end_x,json=endX,proto3" json:"end_x,omitempty"`
	EndY            float64                `protobuf:"fixed64,4,opt,name=end_y,json=endY,proto3" json:"end_y,omitempty"`
	DurationSeconds float64                `protobuf:"fixed64,5,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SwipeEvent) Reset() {
	*x = SwipeEvent{}
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwipeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwipeEvent) ProtoMessage() {}

func (x *SwipeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwipeEvent.ProtoReflect.Descriptor instead.
func (*SwipeEvent) Descriptor() ([]byte, []int) {
	return file_proto_simulator_v1_simulator_proto_rawDescGZIP(), []int{20}
}

func (x *SwipeEvent) GetStartX() float64 {
	if x != nil {
		return x.StartX
	}
	return 0
}

func (x *SwipeEvent) GetStartY() float64 {
	if x != nil {
		return x.StartY
	}
	return 0
}

func (x *SwipeEvent) GetEndX() float64 {
	if x != nil {
		return x.EndX
	}
	return 0
}

func (x *SwipeEvent) GetEndY() float64 {
	if x != nil {
		return x.EndY
	}
	return 0
}

func (x *SwipeEvent) GetDurationSeconds() float64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

type WatchEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEventsRequest) Reset() {
	*x = WatchEventsRequest{}
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEventsRequest) ProtoMessage() {}

func (x *WatchEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEventsRequest.ProtoReflect.Descriptor instead.
func (*WatchEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_simulator_v1_simulator_proto_rawDescGZIP(), []int{21}
}

func (x *WatchEventsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type Event struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TimestampUnixMs int64                  `protobuf:"varint,2,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Event_Status
	//	*Event_Stopped
	//	*Event_Error
	Payload       isEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_simulator_v1_simulator_proto_rawDescGZIP(), []int{22}
}

func (x *Event) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Event) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

func (x *Event) GetPayload() isEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetStatus() *StatusEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *Event) GetStopped() *StoppedEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_Stopped); ok {
			return x.Stopped
		}
	}
	return nil
}

func (x *Event) GetError() *ErrorEvent {
	if x != nil {
		if x, ok := x.Payload.(*Event_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_Status struct {
	Status *StatusEvent `protobuf:"bytes,10,opt,name=status,proto3,oneof"`
}

type Event_Stopped struct {
	Stopped *StoppedEvent `protobuf:"bytes,11,opt,name=stopped,proto3,oneof"`
}

type Event_Error struct {
	Error *ErrorEvent `protobuf:"bytes,12,opt,name=error,proto3,oneof"`
}

func (*Event_Status) isEvent_Payload() {}

func (*Event_Stopped) isEvent_Payload() {}

func (*Event_Error) isEvent_Payload() {}

type StatusEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phase         string                 `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusEvent) Reset() {
	*x = StatusEvent{}
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusEvent) ProtoMessage() {}

func (x *StatusEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusEvent.ProtoReflect.Descriptor instead.
func (*StatusEvent) Descriptor() ([]byte, []int) {
	return file_proto_simulator_v1_simulator_proto_rawDescGZIP(), []int{23}
}

func (x *StatusEvent) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

type StoppedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoppedEvent) Reset() {
	*x = StoppedEvent{}
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoppedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoppedEvent) ProtoMessage() {}

func (x *StoppedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoppedEvent.ProtoReflect.Descriptor instead.
func (*StoppedEvent) Descriptor() ([]byte, []int) {
	return file_proto_simulator_v1_simulator_proto_rawDescGZIP(), []int{24}
}

func (x *StoppedEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *StoppedEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ErrorEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorEvent) Reset() {
	*x = ErrorEvent{}
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorEvent) ProtoMessage() {}

func (x *ErrorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorEvent.ProtoReflect.Descriptor instead.
func (*ErrorEvent) Descriptor() ([]byte, []int) {
	return file_proto_simulator_v1_simulator_proto_rawDescGZIP(), []int{25}
}

func (x *ErrorEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type WatchVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Fps           int32                  `protobuf:"varint,2,opt,name=fps,proto3" json:"fps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchVideoRequest) Reset() {
	*x = WatchVideoRequest{}
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchVideoRequest) ProtoMessage() {}

func (x *WatchVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchVideoRequest.ProtoReflect.Descriptor instead.
func (*WatchVideoRequest) Descriptor() ([]byte, []int) {
	return file_proto_simulator_v1_simulator_proto_rawDescGZIP(), []int{26}
}

func (x *WatchVideoRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WatchVideoRequest) GetFps() int32 {
	if x != nil {
		return x.Fps
	}
	return 0
}

type VideoFrame struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Jpeg            []byte                 `protobuf:"bytes,2,opt,name=jpeg,proto3" json:"jpeg,omitempty"`
	Width           int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height          int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	TimestampUnixMs int64                  `protobuf:"varint,5,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *VideoFrame) Reset() {
	*x = VideoFrame{}
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoFrame) ProtoMessage() {}

func (x *VideoFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simulator_v1_simulator_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoFrame.ProtoReflect.Descriptor instead.
func (*VideoFrame) Descriptor() ([]byte, []int) {
	return file_proto_simulator_v1_simulator_proto_rawDescGZIP(), []int{27}
}

func (x *VideoFrame) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *VideoFrame) GetJpeg() []byte {
	if x != nil {
		return x.Jpeg
	}
	return nil
}

func (x *VideoFrame) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *VideoFrame) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *VideoFrame) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

var File_proto_simulator_v1_simulator_proto protoreflect.FileDescriptor

const file_proto_simulator_v1_simulator_proto_rawDesc = "" +
	"\n" +
	"\"proto/simulator/v1/simulator.proto\x12\x10axe.simulator.v1\"\x0f\n" +
	"\rHealthRequest\"B\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\x14\n" +
	"\x12ListDevicesRequest\"V\n" +
	"\x13ListDevicesResponse\x12?\n" +
	"\fdevice_types\x18\x01 \x03(\v2\x1c.axe.simulator.v1.DeviceTypeR\vdeviceTypes\"w\n" +
	"\n" +
	"DeviceType\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x125\n" +
	"\bruntimes\x18\x03 \x03(\v2\x19.axe.simulator.v1.RuntimeR\bruntimes\"=\n" +
	"\aRuntime\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xe7\x01\n" +
	"\x14CreateSessionRequest\x12\x1f\n" +
	"\vdevice_type\x18\x01 \x01(\tR\n" +
	"deviceType\x12\x18\n" +
	"\aruntime\x18\x02 \x01(\tR\aruntime\x12<\n" +
	"\n" +
	"app_bundle\x18\n" +
	" \x01(\v2\x1b.axe.simulator.v1.AppBundleH\x00R\tappBundle\x12E\n" +
	"\rinstalled_app\x18\v \x01(\v2\x1e.axe.simulator.v1.InstalledAppH\x00R\finstalledAppB\x0f\n" +
	"\rlaunch_target\"<\n" +
	"\tAppBundle\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1b\n" +
	"\tbundle_id\x18\x02 \x01(\tR\bbundleId\"+\n" +
	"\fInstalledApp\x12\x1b\n" +
	"\tbundle_id\x18\x01 \x01(\tR\bbundleId\"L\n" +
	"\x15CreateSessionResponse\x123\n" +
	"\asession\x18\x01 \x01(\v2\x19.axe.simulator.v1.SessionR\asession\"2\n" +
	"\x11GetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"3\n" +
	"\x12StopSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x15\n" +
	"\x13StopSessionResponse\"\x9f\x02\n" +
	"\aSession\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vdevice_udid\x18\x02 \x01(\tR\n" +
	"deviceUdid\x12\x1f\n" +
	"\vdevice_type\x18\x03 \x01(\tR\n" +
	"deviceType\x12\x18\n" +
	"\aruntime\x18\x04 \x01(\tR\aruntime\x124\n" +
	"\x05state\x18\x05 \x01(\x0e2\x1e.axe.simulator.v1.SessionStateR\x05state\x12\x1b\n" +
	"\tbundle_id\x18\x06 \x01(\tR\bbundleId\x12!\n" +
	"\fscreen_width\x18\a \x01(\x05R\vscreenWidth\x12#\n" +
	"\rscreen_height\x18\b \x01(\x05R\fscreenHeight\"e\n" +
	"\x10SendInputRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x122\n" +
	"\x05input\x18\x02 \x01(\v2\x1c.axe.simulator.v1.InputEventR\x05input\"\x13\n" +
	"\x11SendInputResponse\"\xe7\x02\n" +
	"\n" +
	"InputEvent\x12=\n" +
	"\n" +
	"touch_down\x18\x01 \x01(\v2\x1c.axe.simulator.v1.TouchEventH\x00R\ttouchDown\x12=\n" +
	"\n" +
	"touch_move\x18\x02 \x01(\v2\x1c.axe.simulator.v1.TouchEventH\x00R\ttouchMove\x129\n" +
	"\btouch_up\x18\x03 \x01(\v2\x1c.axe.simulator.v1.TouchEventH\x00R\atouchUp\x121\n" +
	"\x04text\x18\x04 \x01(\v2\x1b.axe.simulator.v1.TextEventH\x00R\x04text\x12.\n" +
	"\x03tap\x18\x05 \x01(\v2\x1a.axe.simulator.v1.TapEventH\x00R\x03tap\x124\n" +
	"\x05swipe\x18\x06 \x01(\v2\x1c.axe.simulator.v1.SwipeEventH\x00R\x05swipeB\a\n" +
	"\x05event\"(\n" +
	"\n" +
	"TouchEvent\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\"!\n" +
	"\tTextEvent\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"&\n" +
	"\bTapEvent\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\"\x93\x01\n" +
	"\n" +
	"SwipeEvent\x12\x17\n" +
	"\astart_x\x18\x01 \x01(\x01R\x06startX\x12\x17\n" +
	"\astart_y\x18\x02 \x01(\x01R\x06startY\x12\x13\n" +
	"\x05end_x\x18\x03 \x01(\x01R\x04endX\x12\x13\n" +
	"\x05end_y\x18\x04 \x01(\x01R\x04endY\x12)\n" +
	"\x10duration_seconds\x18\x05 \x01(\x01R\x0fdurationSeconds\"3\n" +
	"\x12WatchEventsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x88\x02\n" +
	"\x05Event\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12*\n" +
	"\x11timestamp_unix_ms\x18\x02 \x01(\x03R\x0ftimestampUnixMs\x127\n" +
	"\x06status\x18\n" +
	" \x01(\v2\x1d.axe.simulator.v1.StatusEventH\x00R\x06status\x12:\n" +
	"\astopped\x18\v \x01(\v2\x1e.axe.simulator.v1.StoppedEventH\x00R\astopped\x124\n" +
	"\x05error\x18\f \x01(\v2\x1c.axe.simulator.v1.ErrorEventH\x00R\x05errorB\t\n" +
	"\apayload\"#\n" +
	"\vStatusEvent\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\"@\n" +
	"\fStoppedEvent\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"&\n" +
	"\n" +
	"ErrorEvent\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"D\n" +
	"\x11WatchVideoRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03fps\x18\x02 \x01(\x05R\x03fps\"\x99\x01\n" +
	"\n" +
	"VideoFrame\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04jpeg\x18\x02 \x01(\fR\x04jpeg\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\x12*\n" +
	"\x11timestamp_unix_ms\x18\x05 \x01(\x03R\x0ftimestampUnixMs*\x99\x01\n" +
	"\fSessionState\x12\x1d\n" +
	"\x19SESSION_STATE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SESSION_STATE_STARTING\x10\x01\x12\x19\n" +
	"\x15SESSION_STATE_RUNNING\x10\x02\x12\x19\n" +
	"\x15SESSION_STATE_STOPPED\x10\x03\x12\x18\n" +
	"\x14SESSION_STATE_FAILED\x10\x042\xc0\x05\n" +
	"\x10SimulatorService\x12K\n" +
	"\x06Health\x12\x1f.axe.simulator.v1.HealthRequest\x1a .axe.simulator.v1.HealthResponse\x12Z\n" +
	"\vListDevices\x12$.axe.simulator.v1.ListDevicesRequest\x1a%.axe.simulator.v1.ListDevicesResponse\x12`\n" +
	"\rCreateSession\x12&.axe.simulator.v1.CreateSessionRequest\x1a'.axe.simulator.v1.CreateSessionResponse\x12L\n" +
	"\n" +
	"GetSession\x12#.axe.simulator.v1.GetSessionRequest\x1a\x19.axe.simulator.v1.Session\x12Z\n" +
	"\vStopSession\x12$.axe.simulator.v1.StopSessionRequest\x1a%.axe.simulator.v1.StopSessionResponse\x12T\n" +
	"\tSendInput\x12\".axe.simulator.v1.SendInputRequest\x1a#.axe.simulator.v1.SendInputResponse\x12N\n" +
	"\vWatchEvents\x12$.axe.simulator.v1.WatchEventsRequest\x1a\x17.axe.simulator.v1.Event0\x01\x12Q\n" +
	"\n" +
	"WatchVideo\x12#.axe.simulator.v1.WatchVideoRequest\x1a\x1c.axe.simulator.v1.VideoFrame0\x01B8Z6github.com/k-kohey/axe/pkg/simulatorapi/v1;simulatorv1b\x06proto3"

var (
	file_proto_simulator_v1_simulator_proto_rawDescOnce sync.Once
	file_proto_simulator_v1_simulator_proto_rawDescData []byte
)

func file_proto_simulator_v1_simulator_proto_rawDescGZIP() []byte {
	file_proto_simulator_v1_simulator_proto_rawDescOnce.Do(func() {
		file_proto_simulator_v1_simulator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_simulator_v1_simulator_proto_rawDesc), len(file_proto_simulator_v1_simulator_proto_rawDesc)))
	})
	return file_proto_simulator_v1_simulator_proto_rawDescData
}

var file_proto_simulator_v1_simulator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_simulator_v1_simulator_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_proto_simulator_v1_simulator_proto_goTypes = []any{
	(SessionState)(0),             // 0: axe.simulator.v1.SessionState
	(*HealthRequest)(nil),         // 1: axe.simulator.v1.HealthRequest
	(*HealthResponse)(nil),        // 2: axe.simulator.v1.HealthResponse
	(*ListDevicesRequest)(nil),    // 3: axe.simulator.v1.ListDevicesRequest
	(*ListDevicesResponse)(nil),   // 4: axe.simulator.v1.ListDevicesResponse
	(*DeviceType)(nil),            // 5: axe.simulator.v1.DeviceType
	(*Runtime)(nil),               // 6: axe.simulator.v1.Runtime
	(*CreateSessionRequest)(nil),  // 7: axe.simulator.v1.CreateSessionRequest
	(*AppBundle)(nil),             // 8: axe.simulator.v1.AppBundle
	(*InstalledApp)(nil),          // 9: axe.simulator.v1.InstalledApp
	(*CreateSessionResponse)(nil), // 10: axe.simulator.v1.CreateSessionResponse
	(*GetSessionRequest)(nil),     // 11: axe.simulator.v1.GetSessionRequest
	(*StopSessionRequest)(nil),    // 12: axe.simulator.v1.StopSessionRequest
	(*StopSessionResponse)(nil),   // 13: axe.simulator.v1.StopSessionResponse
	(*Session)(nil),               // 14: axe.simulator.v1.Session
	(*SendInputRequest)(nil),      // 15: axe.simulator.v1.SendInputRequest
	(*SendInputResponse)(nil),     // 16: axe.simulator.v1.SendInputResponse
	(*InputEvent)(nil),            // 17: axe.simulator.v1.InputEvent
	(*TouchEvent)(nil),            // 18: axe.simulator.v1.TouchEvent
	(*TextEvent)(nil),             // 19: axe.simulator.v1.TextEvent
	(*TapEvent)(nil),              // 20: axe.simulator.v1.TapEvent
	(*SwipeEvent)(nil),            // 21: axe.simulator.v1.SwipeEvent
	(*WatchEventsRequest)(nil),    // 22: axe.simulator.v1.WatchEventsRequest
	(*Event)(nil),                 // 23: axe.simulator.v1.Event
	(*StatusEvent)(nil),           // 24: axe.simulator.v1.StatusEvent
	(*StoppedEvent)(nil),          // 25: axe.simulator.v1.StoppedEvent
	(*ErrorEvent)(nil),            // 26: axe.simulator.v1.ErrorEvent
	(*WatchVideoRequest)(nil),     // 27: axe.simulator.v1.WatchVideoRequest
	(*VideoFrame)(nil),            // 28: axe.simulator.v1.VideoFrame
}
var file_proto_simulator_v1_simulator_proto_depIdxs = []int32{
	5,  // 0: axe.simulator.v1.ListDevicesResponse.device_types:type_name -> axe.simulator.v1.DeviceType
	6,  // 1: axe.simulator.v1.DeviceType.runtimes:type_name -> axe.simulator.v1.Runtime
	8,  // 2: axe.simulator.v1.CreateSessionRequest.app_bundle:type_name -> axe.simulator.v1.AppBundle
	9,  // 3: axe.simulator.v1.CreateSessionRequest.installed_app:type_name -> axe.simulator.v1.InstalledApp
	14, // 4: axe.simulator.v1.CreateSessionResponse.session:type_name -> axe.simulator.v1.Session
	0,  // 5: axe.simulator.v1.Session.state:type_name -> axe.simulator.v1.SessionState
	17, // 6: axe.simulator.v1.SendInputRequest.input:type_name -> axe.simulator.v1.InputEvent
	18, // 7: axe.simulator.v1.InputEvent.touch_down:type_name -> axe.simulator.v1.TouchEvent
	18, // 8: axe.simulator.v1.InputEvent.touch_move:type_name -> axe.simulator.v1.TouchEvent
	18, // 9: axe.simulator.v1.InputEvent.touch_up:type_name -> axe.simulator.v1.TouchEvent
	19, // 10: axe.simulator.v1.InputEvent.text:type_name -> axe.simulator.v1.TextEvent
	20, // 11: axe.simulator.v1.InputEvent.tap:type_name -> axe.simulator.v1.TapEvent
	21, // 12: axe.simulator.v1.InputEvent.swipe:type_name -> axe.simulator.v1.SwipeEvent
	24, // 13: axe.simulator.v1.Event.status:type_name -> axe.simulator.v1.StatusEvent
	25, // 14: axe.simulator.v1.Event.stopped:type_name -> axe.simulator.v1.StoppedEvent
	26, // 15: axe.simulator.v1.Event.error:type_name -> axe.simulator.v1.ErrorEvent
	1,  // 16: axe.simulator.v1.SimulatorService.Health:input_type -> axe.simulator.v1.HealthRequest
	3,  // 17: axe.simulator.v1.SimulatorService.ListDevices:input_type -> axe.simulator.v1.ListDevicesRequest
	7,  // 18: axe.simulator.v1.SimulatorService.CreateSession:input_type -> axe.simulator.v1.CreateSessionRequest
	11, // 19: axe.simulator.v1.SimulatorService.GetSession:input_type -> axe.simulator.v1.GetSessionRequest
	12, // 20: axe.simulator.v1.SimulatorService.StopSession:input_type -> axe.simulator.v1.StopSessionRequest
	15, // 21: axe.simulator.v1.SimulatorService.SendInput:input_type -> axe.simulator.v1.SendInputRequest
	22, // 22: axe.simulator.v1.SimulatorService.WatchEvents:input_type -> axe.simulator.v1.WatchEventsRequest
	27, // 23: axe.simulator.v1.SimulatorService.WatchVideo:input_type -> axe.simulator.v1.WatchVideoRequest
	2,  // 24: axe.simulator.v1.SimulatorService.Health:output_type -> axe.simulator.v1.HealthResponse
	4,  // 25: axe.simulator.v1.SimulatorService.ListDevices:output_type -> axe.simulator.v1.ListDevicesResponse
	10, // 26: axe.simulator.v1.SimulatorService.CreateSession:output_type -> axe.simulator.v1.CreateSessionResponse
	14, // 27: axe.simulator.v1.SimulatorService.GetSession:output_type -> axe.simulator.v1.Session
	13, // 28: axe.simulator.v1.SimulatorService.StopSession:output_type -> axe.simulator.v1.StopSessionResponse
	16, // 29: axe.simulator.v1.SimulatorService.SendInput:output_type -> axe.simulator.v1.SendInputResponse
	23, // 30: axe.simulator.v1.SimulatorService.WatchEvents:output_type -> axe.simulator.v1.Event
	28, // 31: axe.simulator.v1.SimulatorService.WatchVideo:output_type -> axe.simulator.v1.VideoFrame
	24, // [24:32] is the sub-list for method output_type
	16, // [16:24] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_simulator_v1_simulator_proto_init() }
func file_proto_simulator_v1_simulator_proto_init() {
	if File_proto_simulator_v1_simulator_proto != nil {
		return
	}
	file_proto_simulator_v1_simulator_proto_msgTypes[6].OneofWrappers = []any{
		(*CreateSessionRequest_AppBundle)(nil),
		(*CreateSessionRequest_InstalledApp)(nil),
	}
	file_proto_simulator_v1_simulator_proto_msgTypes[16].OneofWrappers = []any{
		(*InputEvent_TouchDown)(nil),
		(*InputEvent_TouchMove)(nil),
		(*InputEvent_TouchUp)(nil),
		(*InputEvent_Text)(nil),
		(*InputEvent_Tap)(nil),
		(*InputEvent_Swipe)(nil),
	}
	file_proto_simulator_v1_simulator_proto_msgTypes[22].OneofWrappers = []any{
		(*Event_Status)(nil),
		(*Event_Stopped)(nil),
		(*Event_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_simulator_v1_simulator_proto_rawDesc), len(file_proto_simulator_v1_simulator_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_simulator_v1_simulator_proto_goTypes,
		DependencyIndexes: file_proto_simulator_v1_simulator_proto_depIdxs,
		EnumInfos:         file_proto_simulator_v1_simulator_proto_enumTypes,
		MessageInfos:      file_proto_simulator_v1_simulator_proto_msgTypes,
	}.Build()
	File_proto_simulator_v1_simulator_proto = out.File
	file_proto_simulator_v1_simulator_proto_goTypes = nil
	file_proto_simulator_v1_simulator_proto_depIdxs = nil
}
