// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: analysis.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum Axe_Analysis_TypeKind: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unknown // = 0
  case `struct` // = 1
  case `class` // = 2
  case `enum` // = 3
  case actor // = 4
  case UNRECOGNIZED(Int)

  public init() {
    self = .unknown
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unknown
    case 1: self = .struct
    case 2: self = .class
    case 3: self = .enum
    case 4: self = .actor
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unknown: return 0
    case .struct: return 1
    case .class: return 2
    case .enum: return 3
    case .actor: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Axe_Analysis_TypeKind] = [
    .unknown,
    .struct,
    .class,
    .enum,
    .actor,
  ]

}

public enum Axe_Analysis_MemberSourceKind: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unknown // = 0
  case property // = 1
  case method // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unknown
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unknown
    case 1: self = .property
    case 2: self = .method
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unknown: return 0
    case .property: return 1
    case .method: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Axe_Analysis_MemberSourceKind] = [
    .unknown,
    .property,
    .method,
  ]

}

public enum Axe_Analysis_MemberKind: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unknown // = 0
  case instanceProperty // = 1
  case instanceMethod // = 2
  case staticProperty // = 3
  case staticMethod // = 4
  case constructor // = 5
  case UNRECOGNIZED(Int)

  public init() {
    self = .unknown
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unknown
    case 1: self = .instanceProperty
    case 2: self = .instanceMethod
    case 3: self = .staticProperty
    case 4: self = .staticMethod
    case 5: self = .constructor
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unknown: return 0
    case .instanceProperty: return 1
    case .instanceMethod: return 2
    case .staticProperty: return 3
    case .staticMethod: return 4
    case .constructor: return 5
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Axe_Analysis_MemberKind] = [
    .unknown,
    .instanceProperty,
    .instanceMethod,
    .staticProperty,
    .staticMethod,
    .constructor,
  ]

}

public struct Axe_Analysis_PropertyInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var name: String = String()

  public var typeExpr: String = String()

  public var bodyLine: Int32 = 0

  public var source: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Axe_Analysis_MethodInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var name: String = String()

  public var selector: String = String()

  public var signature: String = String()

  public var bodyLine: Int32 = 0

  public var source: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Axe_Analysis_TypeInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var name: String = String()

  public var kind: Axe_Analysis_TypeKind = .unknown

  public var accessLevel: String = String()

  public var inheritedTypes: [String] = []

  public var properties: [Axe_Analysis_PropertyInfo] = []

  public var methods: [Axe_Analysis_MethodInfo] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Axe_Analysis_PreviewBlock: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var startLine: Int32 = 0

  public var title: String = String()

  public var source: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Axe_Analysis_MemberSource: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var typeName: String = String()

  public var line: Int32 = 0

  public var kind: Axe_Analysis_MemberSourceKind = .unknown

  public var name: String = String()

  public var typeExpr: String = String()

  public var signature: String = String()

  public var selector: String = String()

  public var bodyLine: Int32 = 0

  public var source: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Axe_Analysis_ParseResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var imports: [String] = []

  public var previews: [Axe_Analysis_PreviewBlock] = []

  public var skeletonHash: String = String()

  public var memberSources: [Axe_Analysis_MemberSource] = []

  /// Parser-derived access levels for type declarations (typeName → "private", "internal", etc.).
  /// Supplements Index Store data which does not reliably report access levels.
  public var typeAccessLevels: Dictionary<String,String> = [:]

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Axe_Analysis_TypeFileMap: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// typeName → filePath
  public var types: Dictionary<String,String> = [:]

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Axe_Analysis_IndexMemberInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// "body", "greet(name:)"
  public var name: String = String()

  public var kind: Axe_Analysis_MemberKind = .unknown

  /// "private", "internal", "public", etc.
  public var accessLevel: String = String()

  public var line: Int32 = 0

  public var column: Int32 = 0

  /// accessor occurrence の有無で判定
  public var isComputed: Bool = false

  /// Unified Symbol Resolution
  public var usr: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Axe_Analysis_IndexTypeInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// ネスト型は "Outer.Inner"
  public var name: String = String()

  /// 既存の TypeKind enum を再利用
  public var kind: Axe_Analysis_TypeKind = .unknown

  public var accessLevel: String = String()

  public var inheritedTypes: [String] = []

  public var members: [Axe_Analysis_IndexMemberInfo] = []

  public var line: Int32 = 0

  public var column: Int32 = 0

  /// Unified Symbol Resolution
  public var usr: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Axe_Analysis_IndexFileData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var filePath: String = String()

  public var types: [Axe_Analysis_IndexTypeInfo] = []

  public var referencedTypeNames: [String] = []

  public var definedTypeNames: [String] = []

  /// Swift module this file belongs to (e.g. "TodoApp", "DSComponents")
  public var moduleName: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Axe_Analysis_IndexStoreResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var files: [Axe_Analysis_IndexFileData] = []

  public var typeFileMap: Dictionary<String,String> = [:]

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "axe.analysis"

extension Axe_Analysis_TypeKind: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0TYPE_KIND_UNKNOWN\0\u{1}TYPE_KIND_STRUCT\0\u{1}TYPE_KIND_CLASS\0\u{1}TYPE_KIND_ENUM\0\u{1}TYPE_KIND_ACTOR\0")
}

extension Axe_Analysis_MemberSourceKind: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0MEMBER_SOURCE_KIND_UNKNOWN\0\u{1}MEMBER_SOURCE_KIND_PROPERTY\0\u{1}MEMBER_SOURCE_KIND_METHOD\0")
}

extension Axe_Analysis_MemberKind: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0MEMBER_KIND_UNKNOWN\0\u{1}MEMBER_KIND_INSTANCE_PROPERTY\0\u{1}MEMBER_KIND_INSTANCE_METHOD\0\u{1}MEMBER_KIND_STATIC_PROPERTY\0\u{1}MEMBER_KIND_STATIC_METHOD\0\u{1}MEMBER_KIND_CONSTRUCTOR\0")
}

extension Axe_Analysis_PropertyInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PropertyInfo"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{3}type_expr\0\u{3}body_line\0\u{1}source\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.typeExpr) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.bodyLine) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.source) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.typeExpr.isEmpty {
      try visitor.visitSingularStringField(value: self.typeExpr, fieldNumber: 2)
    }
    if self.bodyLine != 0 {
      try visitor.visitSingularInt32Field(value: self.bodyLine, fieldNumber: 3)
    }
    if !self.source.isEmpty {
      try visitor.visitSingularStringField(value: self.source, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Axe_Analysis_PropertyInfo, rhs: Axe_Analysis_PropertyInfo) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.typeExpr != rhs.typeExpr {return false}
    if lhs.bodyLine != rhs.bodyLine {return false}
    if lhs.source != rhs.source {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Axe_Analysis_MethodInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MethodInfo"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}selector\0\u{1}signature\0\u{3}body_line\0\u{1}source\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.selector) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.signature) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.bodyLine) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.source) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.selector.isEmpty {
      try visitor.visitSingularStringField(value: self.selector, fieldNumber: 2)
    }
    if !self.signature.isEmpty {
      try visitor.visitSingularStringField(value: self.signature, fieldNumber: 3)
    }
    if self.bodyLine != 0 {
      try visitor.visitSingularInt32Field(value: self.bodyLine, fieldNumber: 4)
    }
    if !self.source.isEmpty {
      try visitor.visitSingularStringField(value: self.source, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Axe_Analysis_MethodInfo, rhs: Axe_Analysis_MethodInfo) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.selector != rhs.selector {return false}
    if lhs.signature != rhs.signature {return false}
    if lhs.bodyLine != rhs.bodyLine {return false}
    if lhs.source != rhs.source {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Axe_Analysis_TypeInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".TypeInfo"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}kind\0\u{3}access_level\0\u{3}inherited_types\0\u{1}properties\0\u{1}methods\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.kind) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.accessLevel) }()
      case 4: try { try decoder.decodeRepeatedStringField(value: &self.inheritedTypes) }()
      case 5: try { try decoder.decodeRepeatedMessageField(value: &self.properties) }()
      case 6: try { try decoder.decodeRepeatedMessageField(value: &self.methods) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if self.kind != .unknown {
      try visitor.visitSingularEnumField(value: self.kind, fieldNumber: 2)
    }
    if !self.accessLevel.isEmpty {
      try visitor.visitSingularStringField(value: self.accessLevel, fieldNumber: 3)
    }
    if !self.inheritedTypes.isEmpty {
      try visitor.visitRepeatedStringField(value: self.inheritedTypes, fieldNumber: 4)
    }
    if !self.properties.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.properties, fieldNumber: 5)
    }
    if !self.methods.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.methods, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Axe_Analysis_TypeInfo, rhs: Axe_Analysis_TypeInfo) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.kind != rhs.kind {return false}
    if lhs.accessLevel != rhs.accessLevel {return false}
    if lhs.inheritedTypes != rhs.inheritedTypes {return false}
    if lhs.properties != rhs.properties {return false}
    if lhs.methods != rhs.methods {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Axe_Analysis_PreviewBlock: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PreviewBlock"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}start_line\0\u{1}title\0\u{1}source\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.startLine) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.title) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.source) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.startLine != 0 {
      try visitor.visitSingularInt32Field(value: self.startLine, fieldNumber: 1)
    }
    if !self.title.isEmpty {
      try visitor.visitSingularStringField(value: self.title, fieldNumber: 2)
    }
    if !self.source.isEmpty {
      try visitor.visitSingularStringField(value: self.source, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Axe_Analysis_PreviewBlock, rhs: Axe_Analysis_PreviewBlock) -> Bool {
    if lhs.startLine != rhs.startLine {return false}
    if lhs.title != rhs.title {return false}
    if lhs.source != rhs.source {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Axe_Analysis_MemberSource: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MemberSource"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}type_name\0\u{1}line\0\u{1}kind\0\u{1}name\0\u{3}type_expr\0\u{1}signature\0\u{1}selector\0\u{3}body_line\0\u{1}source\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.typeName) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.line) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.kind) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.typeExpr) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.signature) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.selector) }()
      case 8: try { try decoder.decodeSingularInt32Field(value: &self.bodyLine) }()
      case 9: try { try decoder.decodeSingularStringField(value: &self.source) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.typeName.isEmpty {
      try visitor.visitSingularStringField(value: self.typeName, fieldNumber: 1)
    }
    if self.line != 0 {
      try visitor.visitSingularInt32Field(value: self.line, fieldNumber: 2)
    }
    if self.kind != .unknown {
      try visitor.visitSingularEnumField(value: self.kind, fieldNumber: 3)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 4)
    }
    if !self.typeExpr.isEmpty {
      try visitor.visitSingularStringField(value: self.typeExpr, fieldNumber: 5)
    }
    if !self.signature.isEmpty {
      try visitor.visitSingularStringField(value: self.signature, fieldNumber: 6)
    }
    if !self.selector.isEmpty {
      try visitor.visitSingularStringField(value: self.selector, fieldNumber: 7)
    }
    if self.bodyLine != 0 {
      try visitor.visitSingularInt32Field(value: self.bodyLine, fieldNumber: 8)
    }
    if !self.source.isEmpty {
      try visitor.visitSingularStringField(value: self.source, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Axe_Analysis_MemberSource, rhs: Axe_Analysis_MemberSource) -> Bool {
    if lhs.typeName != rhs.typeName {return false}
    if lhs.line != rhs.line {return false}
    if lhs.kind != rhs.kind {return false}
    if lhs.name != rhs.name {return false}
    if lhs.typeExpr != rhs.typeExpr {return false}
    if lhs.signature != rhs.signature {return false}
    if lhs.selector != rhs.selector {return false}
    if lhs.bodyLine != rhs.bodyLine {return false}
    if lhs.source != rhs.source {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Axe_Analysis_ParseResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ParseResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{2}imports\0\u{1}previews\0\u{3}skeleton_hash\0\u{4}\u{3}member_sources\0\u{3}type_access_levels\0\u{c}\u{1}\u{1}\u{c}\u{5}\u{1}\u{c}\u{6}\u{1}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try { try decoder.decodeRepeatedStringField(value: &self.imports) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.previews) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.skeletonHash) }()
      case 7: try { try decoder.decodeRepeatedMessageField(value: &self.memberSources) }()
      case 8: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.typeAccessLevels) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.imports.isEmpty {
      try visitor.visitRepeatedStringField(value: self.imports, fieldNumber: 2)
    }
    if !self.previews.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.previews, fieldNumber: 3)
    }
    if !self.skeletonHash.isEmpty {
      try visitor.visitSingularStringField(value: self.skeletonHash, fieldNumber: 4)
    }
    if !self.memberSources.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.memberSources, fieldNumber: 7)
    }
    if !self.typeAccessLevels.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.typeAccessLevels, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Axe_Analysis_ParseResult, rhs: Axe_Analysis_ParseResult) -> Bool {
    if lhs.imports != rhs.imports {return false}
    if lhs.previews != rhs.previews {return false}
    if lhs.skeletonHash != rhs.skeletonHash {return false}
    if lhs.memberSources != rhs.memberSources {return false}
    if lhs.typeAccessLevels != rhs.typeAccessLevels {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Axe_Analysis_TypeFileMap: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".TypeFileMap"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}types\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.types) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.types.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.types, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Axe_Analysis_TypeFileMap, rhs: Axe_Analysis_TypeFileMap) -> Bool {
    if lhs.types != rhs.types {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Axe_Analysis_IndexMemberInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".IndexMemberInfo"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}kind\0\u{3}access_level\0\u{1}line\0\u{1}column\0\u{3}is_computed\0\u{1}usr\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.kind) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.accessLevel) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.line) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.column) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self.isComputed) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.usr) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if self.kind != .unknown {
      try visitor.visitSingularEnumField(value: self.kind, fieldNumber: 2)
    }
    if !self.accessLevel.isEmpty {
      try visitor.visitSingularStringField(value: self.accessLevel, fieldNumber: 3)
    }
    if self.line != 0 {
      try visitor.visitSingularInt32Field(value: self.line, fieldNumber: 4)
    }
    if self.column != 0 {
      try visitor.visitSingularInt32Field(value: self.column, fieldNumber: 5)
    }
    if self.isComputed != false {
      try visitor.visitSingularBoolField(value: self.isComputed, fieldNumber: 6)
    }
    if !self.usr.isEmpty {
      try visitor.visitSingularStringField(value: self.usr, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Axe_Analysis_IndexMemberInfo, rhs: Axe_Analysis_IndexMemberInfo) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.kind != rhs.kind {return false}
    if lhs.accessLevel != rhs.accessLevel {return false}
    if lhs.line != rhs.line {return false}
    if lhs.column != rhs.column {return false}
    if lhs.isComputed != rhs.isComputed {return false}
    if lhs.usr != rhs.usr {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Axe_Analysis_IndexTypeInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".IndexTypeInfo"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}kind\0\u{3}access_level\0\u{3}inherited_types\0\u{1}members\0\u{1}line\0\u{1}column\0\u{1}usr\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.kind) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.accessLevel) }()
      case 4: try { try decoder.decodeRepeatedStringField(value: &self.inheritedTypes) }()
      case 5: try { try decoder.decodeRepeatedMessageField(value: &self.members) }()
      case 6: try { try decoder.decodeSingularInt32Field(value: &self.line) }()
      case 7: try { try decoder.decodeSingularInt32Field(value: &self.column) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.usr) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if self.kind != .unknown {
      try visitor.visitSingularEnumField(value: self.kind, fieldNumber: 2)
    }
    if !self.accessLevel.isEmpty {
      try visitor.visitSingularStringField(value: self.accessLevel, fieldNumber: 3)
    }
    if !self.inheritedTypes.isEmpty {
      try visitor.visitRepeatedStringField(value: self.inheritedTypes, fieldNumber: 4)
    }
    if !self.members.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.members, fieldNumber: 5)
    }
    if self.line != 0 {
      try visitor.visitSingularInt32Field(value: self.line, fieldNumber: 6)
    }
    if self.column != 0 {
      try visitor.visitSingularInt32Field(value: self.column, fieldNumber: 7)
    }
    if !self.usr.isEmpty {
      try visitor.visitSingularStringField(value: self.usr, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Axe_Analysis_IndexTypeInfo, rhs: Axe_Analysis_IndexTypeInfo) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.kind != rhs.kind {return false}
    if lhs.accessLevel != rhs.accessLevel {return false}
    if lhs.inheritedTypes != rhs.inheritedTypes {return false}
    if lhs.members != rhs.members {return false}
    if lhs.line != rhs.line {return false}
    if lhs.column != rhs.column {return false}
    if lhs.usr != rhs.usr {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Axe_Analysis_IndexFileData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".IndexFileData"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}file_path\0\u{1}types\0\u{3}referenced_type_names\0\u{3}defined_type_names\0\u{3}module_name\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.filePath) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.types) }()
      case 3: try { try decoder.decodeRepeatedStringField(value: &self.referencedTypeNames) }()
      case 4: try { try decoder.decodeRepeatedStringField(value: &self.definedTypeNames) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.moduleName) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.filePath.isEmpty {
      try visitor.visitSingularStringField(value: self.filePath, fieldNumber: 1)
    }
    if !self.types.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.types, fieldNumber: 2)
    }
    if !self.referencedTypeNames.isEmpty {
      try visitor.visitRepeatedStringField(value: self.referencedTypeNames, fieldNumber: 3)
    }
    if !self.definedTypeNames.isEmpty {
      try visitor.visitRepeatedStringField(value: self.definedTypeNames, fieldNumber: 4)
    }
    if !self.moduleName.isEmpty {
      try visitor.visitSingularStringField(value: self.moduleName, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Axe_Analysis_IndexFileData, rhs: Axe_Analysis_IndexFileData) -> Bool {
    if lhs.filePath != rhs.filePath {return false}
    if lhs.types != rhs.types {return false}
    if lhs.referencedTypeNames != rhs.referencedTypeNames {return false}
    if lhs.definedTypeNames != rhs.definedTypeNames {return false}
    if lhs.moduleName != rhs.moduleName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Axe_Analysis_IndexStoreResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".IndexStoreResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}files\0\u{3}type_file_map\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.files) }()
      case 2: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.typeFileMap) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.files.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.files, fieldNumber: 1)
    }
    if !self.typeFileMap.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.typeFileMap, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Axe_Analysis_IndexStoreResult, rhs: Axe_Analysis_IndexStoreResult) -> Bool {
    if lhs.files != rhs.files {return false}
    if lhs.typeFileMap != rhs.typeFileMap {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
